### ISSUE TITLE
datastore-indexes-auto.xml ignored in deploy

### ISSUE THREAD

**Issue by gslender** [GoogleCloudPlatform/google-cloud-eclipse#2309] opened 2017-08-20 05:31 UTC
- Cloud Tools for Eclipse version: 1.3.0.201708031339
- Google Cloud SDK version: 166.0.0
- OS: Mac OS X 10.12.5
- Java version: 1.8.0_121

**What did you do?**
Running the Google Cloud Tools for Eclipse and successfully deploying to App Engine Standard. The code is correctly published to the app engine cloud and generally works, but indexes (that are correctly auto-generated by the dev server) are not copied up to the cloud standard. I can manually add indexes to the datastore-indexes.xml and they are created, but auto-generated indexes are not.

My datastore-indexes.xml looks like so --->>
```
<?xml version="1.0" encoding="utf-8"?>
<datastore-indexes autoGenerate="true">
    <datastore-index kind="QuestionData" ancestor="false" source="manual">
        <property name="pid" direction="asc"/>
        <property name="order" direction="asc"/>
    </datastore-index>
</datastore-indexes>
```

My datastore-indexes-auto.xml file looks like so --->>

```
<!-- Indices written at Sun, 20 Aug 2017 10:15:28 AEST -->
<datastore-indexes>
    <!-- Used 1 time in query history -->
    <datastore-index kind="QuestionData" ancestor="false" source="auto">
        <property name="envscope" direction="asc"/>
        <property name="pid" direction="asc"/>
        <property name="order" direction="asc"/>
    </datastore-index>
</datastore-indexes>
```

**What did you expect to see?**
That the datastore-indexes-auto.xml would be used to create additional indexes in my datastore.

**What did you see instead?**
No indexes are created, and it would seem the temp location, such as
 workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/ that is used by the Dev Server isn't seen or used by the Cloud Tools to Deploy, and so indexes are not created as defined in the datastore-indexes-auto.xml file that is created by the Dev Server running.

**Comment by patflynn** [comment] 2017-08-21 13:16
@etanshaul can you take a look to see if this is an issue for native projects in IntelliJ?

**Comment by etanshaul** [comment] 2017-08-21 14:53
@patflynn - this is confirmed to be working in IntelliJ as long as the user selects to update the datastore indexes upon deploy:

![image](https://user-images.githubusercontent.com/1735744/29524832-e3350b40-865e-11e7-87f3-eeb21d78d758.png)

Perhaps the Eclipse implementation is missing similar functionality?

**Comment by patflynn** [comment] 2017-08-21 15:01
@gslender are you checking the 'include optional App Engine config files'?

@elharo I think that checkbox label could be too vague for people to understand what it does.

**Comment by gslender** [comment] 2017-08-21 21:15
@patflynn Yes, my deployment includes a tick on a tick-box labeled "Include optional App Engine configurational files" and other files related to cron, manual index files etc are deployed, but I think the issue is that the normal location for Eclipse to spin up the Dev Server is in a path that might be different to what is used to deploy - so the generated datastore-indexes-auto.xml isn't found or seen by the scripts/deployment tasks (and therefore not combined).

**Comment by gslender** [comment] 2017-08-21 22:05
I've looked more closely at the deploy log outputs (in the Eclipse console) and can definitely see the issue...

The Dev Server deploys/runs in `/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/`

The Cloud Deploy deploys/runs in `/workspace/.metadata/.plugins/com.google.cloud.tools.eclipse.appengine.deploy/tmp/`

Which are very different paths and therefore the dev server's generated index files are never seen, nor used when deploying.

**Comment by elharo** [comment] 2017-08-21 22:15
I'm confused. Why would one expect that anything generated by the development server would be deployed to production? Is that behavior promised or suggested by any of our documentation somewhere, and if so can you point me to that? 

If files need to be autogenerated before deployment, that should probably happen independently of local development server runs.

**Comment by gslender** [comment] 2017-08-21 22:22
@elharo Have a read... https://cloud.google.com/appengine/docs/standard/java/config/indexconfig

**Comment by chanseokoh** [comment] 2017-08-21 22:45
@gslender From you doc you linked,

> the development server maintains a file named `WEB-INF/appengine-generated/datastore-indexes-auto.xml` in your app's `war/` directory.

as you can read above, it is intended that `datastore-indexes-auto.xml` becomes part of your source repo (i.e., in your app's `war/` directory, committing it into your source repo). (At least, that is what I heard from the dev appserver team, which I believe is consistent with the doc.) For now, the workaround I could think of is to put the file under your `WEB-INF/appengine-generated/datastore-indexes-auto.xml`. When deploying, you will see logs like below, confirming it is deployed together:

```
Reading application configuration data...
Aug 21, 2017 6:24:39 PM com.google.apphosting.utils.config.IndexesXmlReader readConfigXml
INFO: Successfully processed .../tmp/1503354279153/staging-work/WEB-INF/appengine-generated/datastore-indexes-auto.xml


Beginning interaction for module default...
0% Scanning for jsp files.
Success.
Temporary staging for module default directory left in .../tmp/1503354279153/staging
Services to deploy:

descriptor:      [.../1503354279153/staging/app.yaml]
source:          [.../tmp/1503354279153/staging]
target project:  [...]
target service:  [default]
target version:  [20170821t182443]
target url:      [https://....appspot.com]


Configurations to update:

descriptor:      [.../tmp/1503354279153/staging/WEB-INF/appengine-generated/index.yaml]
type:            [datastore indexes]
target project:  [...]
```

@patflynn @etanshaul `AppCfg` will automatically process the auto-gen-index file regardless of the "update-the-datastore-indexes" option, based on whether the file exists in the app source repo. Note that we are talking about `WEB-INF/appengine-generated/index.yaml` (or `WEB-INF/datastore-indexes-auto.xml`), not the `WEB-INF/index.yaml` (or `WEB-INF/datastore-index.xml`). @etanshaul since this file is auto-generated and placed by the dev appserver, it is hard to believe that IntelliJ works here, unless IntelliJ runs the dev appserver against the source repo. Can you confirm you you run the server directly on the source repo? FYI, CT4E doesn't — CT4E prepares a tmp directory for a local run, where the dev server creates the `datastore-indexes-auto.xml` file. Therefore, it will be a pretty difficult task for users to manually copy the file from the tmp directory to their app source repo.

**Comment by chanseokoh** [comment] 2017-08-21 22:49
Updated my previous comment, as there was a slight error, so please check the updated comment on GitHub.

**Comment by etanshaul** [comment] 2017-08-21 23:11
Regarding IntelliJ, you are most likely correct @chanseokoh. I didn't read deep enough into the use case originally and didn't test with the auto-generated indexes. IJ also stages in a tmp directory.

**Comment by gslender** [comment] 2017-08-21 23:27
@chanseokoh okay, so agree the workaround is an option, but I suspect I'll eventually have problems where the Dev Server is deployed into a location that has changed. 

As you wrote...
> CT4E prepares a tmp directory for a local run, where the dev server creates the datastore-indexes-auto.xml file. Therefore, it will be a pretty difficult task for users to manually copy the file from the tmp directory to their app source repo when using CT4E.

Do you know if CT4E will keep the dev server run location fairly consistent to add that location to the project source repo?

**Comment by briandealwis** [comment] 2017-08-22 01:42
I wonder if we could somehow flag the server when the `datastore-indexes-auto.xml` differs from the `datastore-indexes.xml`.  An info marker on the `datastore-indexes.xml` or the `appengine-web.xml`?  A dialog or notification on exit?

**Comment by chanseokoh** [comment] 2017-08-22 03:47
@gslender it seems like the dev server in CT4E will use the same temp directory throughout the life cycle of the server, but I can't really guarantee that.

According to the doc you linked:

> It's a good idea to occasionally move index configuration from `datastore-indexes-auto.xml` to `datastore-indexes.xml`, then disable automatic index configuration and test your app in the development server. This makes it easy to maintain indexes without having to manage two files, and ensures that your testing will reproduce errors caused by missing index configuration.
>
> #### Creating indexes manually
>
> You can add indexes to your `datastore-indexes.xml` file manually or you might shift indexes that the development server had automatically created in the `datastore-indexes-auto.xml` file into your `datastore-indexes.xml` file.

I think it's desired to ultimately put all indexes that your app required into `datastore-indexes.xml` and do not rely on `datastore-indexes-auto.xml`. Hopefully, your app is stable (in terms of index changes) during dev and you don't have to copy `datastore-indexes-auto.xml` to your source repo or migrate the auto-gen indexes to `datastore-indexes.xml` often. As the doc says, there is no reason to maintain the two files once your app reaches a stable state.

**Comment by gslender** [comment] 2017-08-22 04:12
@chanseokoh I agree and then just wished that CT4E didn't put any of the dev server run or deploy into those crazy tmp locations?? It isn't helpful and really annoying for cases like this. I'd rather this choice be optional (where it defaults to self-assigned tmp locations) or I can specify a path to reuse in my repo. Just seems bonkers that this approach was taken that has now caused further issues, but added no value in that step... annoying right?

**Comment by patflynn** [comment] 2017-08-22 09:56
The auto-generated datastore indexes from the devappserver should be included in IDE deployments. This is how the old tooling works and is clearly documented, and I believe this is how our new Gradle and Maven plugins work as well. @loosebazooka can you confirm that we are doing things properly in build tools?

**Comment by patflynn** [comment] 2017-08-22 10:04
@chanseokoh FYI the devappserver runs on an exploded war build output directory and generates the auto-generated files into that build output and not source.    As long as IntelliJ is staging the build output path that the devappserver ran against the auto-generated indexes should be included in the deployment.

**Comment by chanseokoh** [comment] 2017-08-22 10:12
@patflynn I am well aware that our build tools and IDE plugins don't run the dev appserver against the source repo and hence not generating the `datasource-indexes-auto.xml` into users' app source repo. On the other hand, Éamonn was insisting that the dev appserver should be run on the source and not on the build output, so that the generated XML becomes part of the source repo, which is what the official doc (https://cloud.google.com/appengine/docs/standard/java/config/indexconfig) says from what I can see.

**Comment by patflynn** [comment] 2017-08-22 10:37
I don't believe that you can run the devappserver against source. It
requires a built exploded war directory to run.  Perhaps
@eamonnmcmanus meant that you need to specify the --generated_dir flag to
point into your source?


That's not something I'm aware of users doing often.

**Comment by patflynn** [comment] 2017-08-22 10:42
As for the docs I assumed that `war/ directory` was referring to the projects war build output.

Hopefully @eamonnmcmanus can clarify.

**Comment by elharo** [comment] 2017-08-22 13:17
We're going to have to look into this and figure out what to do. Clearly we should make it easier to find datastore-indexes-auto.xml.

That said, I find the workflow in the deeper tooling...troublesome. Automatically deploying a config file the user never sees, may not know about, that isn't checked into their source tree, and whose contents are determined by which queries they did and did not run while manually testing on a local server? That's setting off red flashing alarm bells in my head right now.

**Comment by gslender** [comment] 2017-08-23 03:18
@elharo this isn't a new thing in App Engine - all of the other platform tools have this approach to automatically creating indexes too, so don't be too alarmed or put off by how that works... 
https://cloud.google.com/appengine/docs/standard/python/config/indexconfig

I've been relying on that feature for years and hasn't been a problem until now, when the current CT4E changed how that tooling workflow interacts

**Comment by elharo** [comment] 2017-08-23 09:49
Most of the different platform tools use the same underlying code so this doesn't surprise me. And it's not the autogeneration that concerns me. That seems like a useful tool. But deploying that file automatically seems like it would risk unexpected, hard-to-reproduce problems.

**Comment by patflynn** [comment] 2017-08-23 09:52
It certainly has the potential to do that.  However a lot of existing users depend on it and it's not the new tool suites intention to change that behavior.  

We should fix this in Eclipse and verify that the other plugins don't have the same issue.

@etanshaul 
@loosebazooka 
@elharo 
@chanseokoh

**Comment by briandealwis** [comment] 2018-04-26 03:17
I think [my suggestion](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/2309#issuecomment-323895844) provides a good workflow:
   - on server stop, we check for the `datastore-indexes-auto.xml` file
   - if it differs from the `datastore-indexes.xml` then we create a problem marker on the `datastore-indexes.xml`
   - we provide a quick-fix on this problem marker to merge the changes into `datastore-indexes.xml` and remove the problem marker

**Closed** 2018-05-08 18:31 UTC
Labels: enhancement, high priority
