### ISSUE TITLE
Adding Objectify 6 to native project doesn't add all dependencies pulled in when added to Maven project

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#3428] opened 2019-05-14 21:46 UTC
This leads to an error when launching the local server.

1. Create a native (non-Maven) Java 8 Servlet 3.1 App Engine app with checking _Objectify_.
2. _Run As_ > _App Engine_

```
2019-05-14 17:32:42.273:WARN:oejw.WebAppContext:main: Failed startup of context c.g.a.t.d.j.DevAppEngineWebAppContext@41fecb8b{/,file:///usr/local/google/home/chanseok/runtime-gcloud-eclipse/.metadata/.plugins/org.eclipse.wst.server.core/tmp3/aaa/,UNAVAILABLE}{/usr/local/google/home/chanseok/runtime-gcloud-eclipse/.metadata/.plugins/org.eclipse.wst.server.core/tmp3/aaa}
java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/JsonFactory
	at com.google.api.client.json.jackson2.JacksonFactory.<init>(JacksonFactory.java:44)
	at com.google.api.client.json.jackson2.JacksonFactory$InstanceHolder.<clinit>(JacksonFactory.java:64)
	at com.google.api.client.json.jackson2.JacksonFactory.getDefaultInstance(JacksonFactory.java:59)
	at com.google.auth.oauth2.OAuth2Utils.<clinit>(OAuth2Utils.java:72)
	at com.google.auth.oauth2.GoogleCredentials.getApplicationDefault(GoogleCredentials.java:100)
	at com.google.cloud.ServiceOptions.defaultCredentials(ServiceOptions.java:298)
	at com.google.cloud.ServiceOptions.<init>(ServiceOptions.java:272)
	at com.google.cloud.datastore.DatastoreOptions.<init>(DatastoreOptions.java:102)
	at com.google.cloud.datastore.DatastoreOptions.<init>(DatastoreOptions.java:35)
	at com.google.cloud.datastore.DatastoreOptions$Builder.build(DatastoreOptions.java:89)
	at com.google.cloud.datastore.DatastoreOptions.getDefaultInstance(DatastoreOptions.java:158)
	at com.googlecode.objectify.ObjectifyFactory.<init>(ObjectifyFactory.java:84)
	at com.googlecode.objectify.ObjectifyService.init(ObjectifyService.java:22)
	at ObjectifyWebListener.contextInitialized(ObjectifyWebListener.java:12)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:957)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:552)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:922)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:364)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1497)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1459)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:852)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:278)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:545)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:108)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
	at org.eclipse.jetty.server.Server.start(Server.java:415)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:108)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.server.Server.doStart(Server.java:382)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at com.google.appengine.tools.development.jetty9.JettyContainerService.startContainer(JettyContainerService.java:343)
	at com.google.appengine.tools.development.AbstractContainerService.startup(AbstractContainerService.java:283)
	at com.google.appengine.tools.development.AutomaticInstanceHolder.startUp(AutomaticInstanceHolder.java:26)
	at com.google.appengine.tools.development.AbstractModule.startup(AbstractModule.java:87)
	at com.google.appengine.tools.development.Modules.startup(Modules.java:105)
	at com.google.appengine.tools.development.DevAppServerImpl.doStart(DevAppServerImpl.java:282)
	at com.google.appengine.tools.development.DevAppServerImpl.access$000(DevAppServerImpl.java:47)
	at com.google.appengine.tools.development.DevAppServerImpl$1.run(DevAppServerImpl.java:223)
	at com.google.appengine.tools.development.DevAppServerImpl$1.run(DevAppServerImpl.java:221)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.google.appengine.tools.development.DevAppServerImpl.start(DevAppServerImpl.java:221)
	at com.google.appengine.tools.development.DevAppServerMain$StartAction.apply(DevAppServerMain.java:404)
	at com.google.appengine.tools.util.Parser$ParseResult.applyArgs(Parser.java:45)
	at com.google.appengine.tools.development.DevAppServerMain.run(DevAppServerMain.java:257)
	at com.google.appengine.tools.development.DevAppServerMain.main(DevAppServerMain.java:248)
Caused by: 
java.lang.ClassNotFoundException: com.fasterxml.jackson.core.JsonFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at com.google.appengine.tools.development.IsolatedAppClassLoader.loadClass(IsolatedAppClassLoader.java:208)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.google.api.client.json.jackson2.JacksonFactory.<init>(JacksonFactory.java:44)
	at com.google.api.client.json.jackson2.JacksonFactory$InstanceHolder.<clinit>(JacksonFactory.java:64)
	at com.google.api.client.json.jackson2.JacksonFactory.getDefaultInstance(JacksonFactory.java:59)
	at com.google.auth.oauth2.OAuth2Utils.<clinit>(OAuth2Utils.java:72)
	at com.google.auth.oauth2.GoogleCredentials.getApplicationDefault(GoogleCredentials.java:100)
	at com.google.cloud.ServiceOptions.defaultCredentials(ServiceOptions.java:298)
	at com.google.cloud.ServiceOptions.<init>(ServiceOptions.java:272)
	at com.google.cloud.datastore.DatastoreOptions.<init>(DatastoreOptions.java:102)
	at com.google.cloud.datastore.DatastoreOptions.<init>(DatastoreOptions.java:35)
	at com.google.cloud.datastore.DatastoreOptions$Builder.build(DatastoreOptions.java:89)
	at com.google.cloud.datastore.DatastoreOptions.getDefaultInstance(DatastoreOptions.java:158)
	at com.googlecode.objectify.ObjectifyFactory.<init>(ObjectifyFactory.java:84)
	at com.googlecode.objectify.ObjectifyService.init(ObjectifyService.java:22)
	at ObjectifyWebListener.contextInitialized(ObjectifyWebListener.java:12)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:957)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:552)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:922)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:364)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1497)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1459)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:852)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:278)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:545)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:108)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
	at org.eclipse.jetty.server.Server.start(Server.java:415)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:108)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.server.Server.doStart(Server.java:382)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at com.google.appengine.tools.development.jetty9.JettyContainerService.startContainer(JettyContainerService.java:343)
	at com.google.appengine.tools.development.AbstractContainerService.startup(AbstractContainerService.java:283)
	at com.google.appengine.tools.development.AutomaticInstanceHolder.startUp(AutomaticInstanceHolder.java:26)
	at com.google.appengine.tools.development.AbstractModule.startup(AbstractModule.java:87)
	at com.google.appengine.tools.development.Modules.startup(Modules.java:105)
	at com.google.appengine.tools.development.DevAppServerImpl.doStart(DevAppServerImpl.java:282)
	at com.google.appengine.tools.development.DevAppServerImpl.access$000(DevAppServerImpl.java:47)
	at com.google.appengine.tools.development.DevAppServerImpl$1.run(DevAppServerImpl.java:223)
	at com.google.appengine.tools.development.DevAppServerImpl$1.run(DevAppServerImpl.java:221)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.google.appengine.tools.development.DevAppServerImpl.start(DevAppServerImpl.java:221)
	at com.google.appengine.tools.development.DevAppServerMain$StartAction.apply(DevAppServerMain.java:404)
	at com.google.appengine.tools.util.Parser$ParseResult.applyArgs(Parser.java:45)
	at com.google.appengine.tools.development.DevAppServerMain.run(DevAppServerMain.java:257)
	at com.google.appengine.tools.development.DevAppServerMain.main(DevAppServerMain.java:248)
2019-05-14 17:32:42.276:INFO:oejs.session:main: DefaultSessionIdManager workerName=node0
```

I see that a couple dependencies are missing. For the native project, this is the list of dependencies added by Objectify 6.0.3, which lacks `jackson-core-2.1.3`:

![Selection_010](https://user-images.githubusercontent.com/10523105/57734370-b9132d80-766f-11e9-85fc-03baf356452a.png)

OTOH, for a Maven project:

![Selection_008](https://user-images.githubusercontent.com/10523105/57734391-c6301c80-766f-11e9-8c48-586d032d7392.png)

**Comment by elharo** [comment] 2019-05-20 17:24
I wonder if that dependency is marked optional?

**Comment by elharo** [comment] 2019-05-20 17:33
suspect this is an issue in `BuildPath.addNativeLibrary` or methods downstream of it

**Comment by elharo** [comment] 2019-05-20 18:03
Versions might be different too. It might be this is a result of the Maven project usingt google-cloud-bom and native projects not doing that.

**Comment by elharo** [comment] 2019-05-20 18:05
For a maven project:

[INFO] -------------------------< com.google.test:qa >-------------------------
[INFO] Building qa 0.1.0-SNAPSHOT
[INFO] --------------------------------[ war ]---------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ qa ---
[INFO] com.google.test:qa:war:0.1.0-SNAPSHOT
[INFO] +- javax.servlet:javax.servlet-api:jar:3.1.0:provided
[INFO] +- javax.servlet.jsp:javax.servlet.jsp-api:jar:2.3.1:provided
[INFO] +- jstl:jstl:jar:1.2:compile
[INFO] +- com.googlecode.objectify:objectify:jar:6.0.3:compile
[INFO] |  +- net.spy:spymemcached:jar:2.12.3:compile
[INFO] |  +- com.google.cloud:google-cloud-datastore:jar:1.74.0:compile
[INFO] |  |  +- com.google.cloud:google-cloud-core:jar:1.74.0:compile
[INFO] |  |  |  +- com.google.guava:guava:jar:27.1-android:compile
[INFO] |  |  |  |  +- com.google.guava:failureaccess:jar:1.0.1:compile
[INFO] |  |  |  |  +- com.google.guava:listenablefuture:jar:9999.0-empty-to-avoid-conflict-with-guava:compile
[INFO] |  |  |  |  +- org.checkerframework:checker-compat-qual:jar:2.5.2:compile
[INFO] |  |  |  |  \- com.google.j2objc:j2objc-annotations:jar:1.1:compile
[INFO] |  |  |  +- com.google.http-client:google-http-client:jar:1.29.1:compile
[INFO] |  |  |  |  \- org.apache.httpcomponents:httpclient:jar:4.5.5:compile
[INFO] |  |  |  |     +- org.apache.httpcomponents:httpcore:jar:4.4.9:compile
[INFO] |  |  |  |     +- commons-logging:commons-logging:jar:1.2:compile
[INFO] |  |  |  |     \- commons-codec:commons-codec:jar:1.10:compile
[INFO] |  |  |  +- com.google.code.findbugs:jsr305:jar:3.0.2:compile
[INFO] |  |  |  +- com.google.api:api-common:jar:1.8.1:compile
[INFO] |  |  |  +- com.google.api:gax:jar:1.44.0:compile
[INFO] |  |  |  |  \- org.threeten:threetenbp:jar:1.3.3:compile
[INFO] |  |  |  +- com.google.protobuf:protobuf-java-util:jar:3.7.1:compile
[INFO] |  |  |  +- com.google.api.grpc:proto-google-common-protos:jar:1.15.0:compile
[INFO] |  |  |  \- com.google.api.grpc:proto-google-iam-v1:jar:0.12.0:compile
[INFO] |  |  +- com.google.cloud:google-cloud-core-http:jar:1.74.0:compile
[INFO] |  |  |  +- com.google.auth:google-auth-library-credentials:jar:0.15.0:compile
[INFO] |  |  |  +- com.google.auth:google-auth-library-oauth2-http:jar:0.15.0:compile
[INFO] |  |  |  |  \- com.google.http-client:google-http-client-jackson2:jar:1.29.0:compile
[INFO] |  |  |  |     \- com.fasterxml.jackson.core:jackson-core:jar:2.9.6:compile
[INFO] |  |  |  +- com.google.api-client:google-api-client:jar:1.28.0:compile
[INFO] |  |  |  |  \- com.google.http-client:google-http-client-apache:jar:2.0.0:compile
[INFO] |  |  |  +- com.google.http-client:google-http-client-appengine:jar:1.29.1:compile
[INFO] |  |  |  +- com.google.api:gax-httpjson:jar:0.61.0:compile
[INFO] |  |  |  +- io.opencensus:opencensus-api:jar:0.19.2:compile
[INFO] |  |  |  \- io.opencensus:opencensus-contrib-http-util:jar:0.19.2:compile
[INFO] |  |  +- com.google.api.grpc:proto-google-cloud-datastore-v1:jar:0.57.0:compile
[INFO] |  |  |  \- com.google.protobuf:protobuf-java:jar:3.7.1:compile
[INFO] |  |  +- com.google.cloud.datastore:datastore-v1-proto-client:jar:1.6.0:compile
[INFO] |  |  |  +- com.google.http-client:google-http-client-protobuf:jar:1.20.0:compile
[INFO] |  |  |  +- com.google.http-client:google-http-client-jackson:jar:1.20.0:compile
[INFO] |  |  |  |  \- org.codehaus.jackson:jackson-core-asl:jar:1.9.11:compile
[INFO] |  |  |  \- com.google.oauth-client:google-oauth-client:jar:1.20.0:compile
[INFO] |  |  +- io.grpc:grpc-core:jar:1.19.0:compile
[INFO] |  |  |  +- io.grpc:grpc-context:jar:1.19.0:compile
[INFO] |  |  |  +- com.google.code.gson:gson:jar:2.7:compile
[INFO] |  |  |  +- com.google.errorprone:error_prone_annotations:jar:2.2.0:compile
[INFO] |  |  |  +- org.codehaus.mojo:animal-sniffer-annotations:jar:1.17:compile
[INFO] |  |  |  \- io.opencensus:opencensus-contrib-grpc-metrics:jar:0.19.2:compile
[INFO] |  |  \- javax.annotation:javax.annotation-api:jar:1.3.2:compile
[INFO] |  \- org.slf4j:slf4j-api:jar:1.7.25:compile
[INFO] \- junit:junit:jar:4.12:test
[INFO]    \- org.hamcrest:hamcrest-core:jar:1.3:test

**Comment by elharo** [comment] 2019-05-20 18:09
@chanseok Can you double check this? I'm not se4eing the same results in a Maven project that you are. E.g. I see Guava 27.1-android and you see 20.0.

**Comment by elharo** [comment] 2019-05-20 18:21
When running local server with native app, I get 


HTTP ERROR 503
Problem accessing /. Reason:

    Service Unavailable

**Comment by elharo** [comment] 2019-05-20 18:26
This jackson class gets pulled in by com.google.http-client:google-http-client-jackson2:1.23.0 which does declare a non-optional dependency on 

```
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-core</artifactId>
    </dependency>
```

so I don't know why this isn't working. 

https://search.maven.org/artifact/com.google.http-client/google-http-client-jackson2/1.23.0/jar

**Comment by chanseokoh** [comment] 2019-05-20 19:43
For whatever reason, I start to see Guava 27 for Maven projects. But still 20 for native projects.

**Comment by elharo** [comment] 2019-05-20 20:41
This is returned by DependencyResolver._getTransitiveDependencies

[com.googlecode.objectify:objectify:jar:6.0.3, net.spy:spymemcached:jar:2.12.3, com.google.cloud:google-cloud-datastore:jar:1.16.0, com.google.cloud:google-cloud-core:jar:1.16.0, com.google.guava:guava:jar:20.0, com.google.http-client:google-http-client:jar:1.23.0, org.apache.httpcomponents:httpclient:jar:4.0.1, org.apache.httpcomponents:httpcore:jar:4.0.1, commons-logging:commons-logging:jar:1.1.1, commons-codec:commons-codec:jar:1.3, com.google.code.findbugs:jsr305:jar:3.0.1, com.google.api:api-common:jar:1.2.0, com.google.api:gax:jar:1.17.0, org.threeten:threetenbp:jar:1.3.3, com.google.protobuf:protobuf-java-util:jar:3.5.1, com.google.code.gson:gson:jar:2.7, com.google.api.grpc:proto-google-common-protos:jar:1.0.5, com.google.api.grpc:proto-google-iam-v1:jar:0.1.29, com.google.cloud:google-cloud-core-http:jar:1.16.0, com.google.auth:google-auth-library-credentials:jar:0.9.0, com.google.auth:google-auth-library-oauth2-http:jar:0.9.0, com.google.oauth-client:google-oauth-client:jar:1.23.0, com.google.api-client:google-api-client:jar:1.23.0, com.google.http-client:google-http-client-appengine:jar:1.23.0, com.google.http-client:google-http-client-jackson:jar:1.23.0, org.codehaus.jackson:jackson-core-asl:jar:1.9.11, com.google.http-client:google-http-client-jackson2:jar:1.23.0, com.google.api:gax-httpjson:jar:0.34.0, com.google.api.grpc:proto-google-cloud-datastore-v1:jar:0.1.29, com.google.protobuf:protobuf-java:jar:3.4.0, com.google.cloud.datastore:datastore-v1-proto-client:jar:1.6.0, com.google.http-client:google-http-client-protobuf:jar:1.20.0, org.slf4j:slf4j-api:jar:1.7.25]

**Comment by elharo** [comment] 2019-05-20 20:44
That is, it really looks like we're not getting jackson-core back from m2e. It may bve our request is looking in the wrong repo or not using the right scope. Currenlty the scope is runtime.

**Comment by elharo** [comment] 2019-05-20 21:54
This is the problem:

```
    DependencyFilter filter =
        new AndDependencyFilter(DependencyFilterUtils.classpathFilter(JavaScopes.RUNTIME),
            new NonOptionalDependencyFilter());
```


Turning the filter off lets Jackson get in. I think something higher in the tree is pulling a different version of jackson-core but it's runtime scoped or optional and we don't notice the non-runtime, non-optional sco-pe version elsewhere in the tree.

**Comment by elharo** [comment] 2019-05-20 22:05
The problem is the NonOptionalDependencyFilter. Somehow this dependency is marked as optional.

**Comment by elharo** [comment] 2019-05-20 22:17
FYI the pom.xml for Objectify 6.0 declares jackson-core as optional:

```
	<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-core</artifactId>
			<version>2.9.1</version>
			<scope>compile</scope>
			<optional>true</optional>
		</dependency>
```

**Closed** 2019-05-22 10:39 UTC
Labels: bug, max priority
