### ISSUE TITLE
Use CloudSdk output to show deploy progress

### ISSUE THREAD

**Issue by akerekes** [GoogleCloudPlatform/google-cloud-eclipse#370] opened 2016-07-15 16:30 UTC
When the deploy is executed by the user, if the output received from CloudSdk would be parsed and used as an indicator of the progress we could provide a smoother UX for the progress bar displayed during the deploy job execution.

This requires standard/error output listeners to be added to the CloudSdk instance used by the staging and deploy steps.

**Comment by chanseokoh** [comment] 2016-11-03 22:33
Duplicate of #578.

**Closed by chanseokoh** 2016-11-03 22:33 UTC
Labels: duplicate, enhancement, low priority
