### ISSUE TITLE
Elements are not formatting after adding new maven dependencies

### ISSUE THREAD

**Issue by lak-proddev** [GoogleCloudPlatform/google-cloud-eclipse#3495] opened 2019-06-25 14:18 UTC
STEPS:
1.Create a new  Maven project 
2. Add new libraries from build path
3.Open "pom.xml". 
You will see newly added dependencies are not formatted. as other elements

![image](https://user-images.githubusercontent.com/39690425/60106065-22fc1800-9782-11e9-9161-5843ca877616.png)

**Comment by elharo** [comment] 2019-06-25 14:48
Pretty sure this is a dupe. I'll have ti hunt down the other issue when I get a minute.

**Comment by briandealwis** [comment] 2019-06-25 16:27
Duplicate of #3381

**Comment by briandealwis** [comment] 2019-06-25 16:28
It is somewhat annoying.  I wonder if the XML formatter provides a way to apply the formatter but only to the changed lines.

**Closed by briandealwis** 2019-06-25 16:28 UTC
