### ISSUE TITLE
Flaky test estStandardFacetInstallation(com.google.cloud.tools.eclipse.appengine.facets.StandardFacetInstallationTest)

### ISSUE THREAD

**Issue by akerekes** [GoogleCloudPlatform/google-cloud-eclipse#1449] opened 2017-02-21 15:53 UTC
Failed only on Oxygen for `continuous-integration/travis-ci/push`
https://travis-ci.org/GoogleCloudPlatform/google-cloud-eclipse/jobs/203841847

```
testStandardFacetInstallation(com.google.cloud.tools.eclipse.appengine.facets.StandardFacetInstallationTest)  Time elapsed: 6.553 sec  <<< FAILURE!
java.lang.AssertionError: Imported projects have errors
/test-dynamic-web-project/war/WEB-INF/web.xml:1: Referenced file contains errors (http://java.sun.com/xml/ns/javaee/web-app_2_5.xsd).  For more information, right click on the message in the Problems View and select "Show Details..."
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.google.cloud.tools.eclipse.test.util.project.ProjectUtils.failIfBuildErrors(ProjectUtils.java:139)
	at com.google.cloud.tools.eclipse.test.util.project.ProjectUtils.failIfBuildErrors(ProjectUtils.java:133)
	at com.google.cloud.tools.eclipse.test.util.project.ProjectUtils.importProjects(ProjectUtils.java:119)
	at com.google.cloud.tools.eclipse.appengine.facets.StandardFacetInstallationTest.testStandardFacetInstallation(StandardFacetInstallationTest.java:71)
```

**Comment by chanseokoh** [comment] 2017-02-21 16:31
Duplicate of #1196.

**Closed by chanseokoh** 2017-02-21 16:31 UTC
Labels: testing
