### ISSUE TITLE
Install on Error?

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#2786] opened 2018-02-12 21:17 UTC
Should we try an automatic install when we try to do something and fail like this?

![image](https://user-images.githubusercontent.com/1005544/36120114-26112134-1010-11e8-8d62-a84eb56bad81.png)

**Comment by briandealwis** [comment] 2018-02-13 18:07
Duplicate of #2755

**Closed by briandealwis** 2018-02-13 18:07 UTC
