### ISSUE TITLE
Get freemarker from maven central if possible

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1263] opened 2017-01-21 13:14 UTC
rather than bundling it

**Comment by elharo** [comment] 2017-01-22 15:30
If there's some reason we can't just depend on this (possible) here's a trick for pulling it in from maven central anyway:

https://github.com/jbosstools/jbosstools-freemarker/blob/master/plugins/org.jboss.ide.eclipse.freemarker/pom.xml

**Comment by chanseokoh** [comment] 2017-01-22 15:39
I verified we can pull it in the usual way of ours: #1266 (duplicate of #1270).

**Closed** 2017-01-24 22:13 UTC
Labels: build, Tech Debt
