### ISSUE TITLE
local run - should set or use gcloud beta auth application-default 

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/google-cloud-eclipse#588] opened 2016-08-17 20:07 UTC
Some kind of support for default credentials is required.

`gcloud beta auth application-default` is the `gcloud` way to do this.

This allows for access to google APIs and services

**Comment by elharo** [comment] 2016-08-17 22:19
https://developers.google.com/identity/protocols/application-default-credentials

**Comment by elharo** [comment] 2016-08-29 12:01
@lesv Can you give us an example of a specific operation a user might attempt to perform in Eclipse that would fail due to the lack of application default credentials?

**Comment by lesv** [comment] 2016-08-29 19:11
When you run your app locally (for debug purposes), but need to access remote resources, such as Datastore, PubSub, Cloud Bigtable, any of the management API's, Tensor Flow, Vision or Speech API's, etc.

**Comment by elharo** [comment] 2016-08-29 19:51
I wonder if there's a way we can use the user's existing login credentials for this.

For a single account that's likely to be the case anyway. Why make them login twice?

**Comment by lesv** [comment] 2016-08-29 21:47
We might wish to take this discussion internal soon, but as I understood it, there was a belief that a user might wish to have one level of access for managing projects, and another based on a service account or IAM.  It was originally the way you would like.

You might wish to check w/ the gcloud PM about this.  I could imagine a [x] box (default unchecked) that also set the application-default credentials, but I'd check with the folks who asked that it be broken out before doing it.

**Comment by chanseokoh** [comment] 2017-10-17 23:05
I believe #2352 is a duplicate of this.

There is a workaround now if users really want to provide a credential: https://github.com/GoogleCloudPlatform/google-cloud-eclipse/pull/2354

**Closed by chanseokoh** 2017-10-17 23:05 UTC
Labels: enhancement
