### ISSUE TITLE
After logging in message feels cryptic

### ISSUE THREAD

**Issue by branflake2267** [GoogleCloudPlatform/google-cloud-eclipse#939] opened 2016-11-03 00:15 UTC
The message felt cryptic, what does it mean? I know it means I'm logged in, but maybe it should say that instead of sounds like it sent me an email verification. 

<img width="748" alt="screen shot 2016-11-02 at 5 14 30 pm" src="https://cloud.githubusercontent.com/assets/1326504/19952092/e9301474-a11f-11e6-8a59-1b9e9094f19a.png">

Maybe not a big deal.

**Comment by branflake2267** [comment] 2016-11-03 00:22
A link to the Google Accounts Contacted apps might be appropriate here too. 
https://security.google.com/settings/security/permissions?utm_source=OGB&pli=1

**Comment by chanseokoh** [comment] 2016-11-03 01:58
This is something we certainly need to fix. It's a duplicate of #557, but it's good to know such a link. I'll reference it in #557.

**Closed by chanseokoh** 2016-11-03 01:58 UTC
Labels: duplicate
