### ISSUE TITLE
Trying to deploy

### ISSUE THREAD

**Issue by AIMMOTH** [GoogleCloudPlatform/google-cloud-eclipse#3149] opened 2018-06-10 18:40 UTC
[Installing Google Cloud SDK]
Welcome to the Google Cloud SDK!

Your current Cloud SDK version is: 204.0.0
Installing components from version: 204.0.0

ERROR: (gcloud.components.update) Your current working directory is inside the Cloud SDK install root: C:\Users\Carls Dator\AppData\Local\Google\ct4j-cloud-sdk\LATEST\google-cloud-sdk.  In order to perform this update, run the command from outside of this directory.

This will install all the core command line tools necessary for working with
the Google Cloud Platform.

**Comment by elharo** [comment] 2018-06-10 18:51
This is a duplicate of https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/3131

We plan to fix it in the next release. Meanwhile if you manually install the cloud SDK as described on https://cloud.google.com/eclipse/docs/manage-sdk#self-managed_sdk you should avoid this problem.

**Comment by AIMMOTH** [comment] 2018-06-10 18:51
Re-installing worked. Thanks.

**Closed by elharo** 2018-06-10 18:51 UTC
Labels: duplicate
