### ISSUE TITLE
Quickfix does not appear

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#3452] opened 2019-06-06 18:38 UTC
Back in Eclipse, use the wizard to create a new Google App Engine Standard Java project.

Verify there are no build errors in the project, and no warnings except possibly a couple about serialVersionUID.

In HelloAppEngine.java change

response.getWriter().print("Hello App Engine!\r\n");

to

LogServiceException ex = new LogServiceException(" _Today's date_");
response.getWriter().print("Hello App Engine on " + ex.getMessage() + "\r\n");

Use the quickfix to import LogServiceException and save the file.

**Comment by elharo** [comment] 2019-06-06 18:40
![image](https://user-images.githubusercontent.com/1005544/59057696-fd59ae00-8868-11e9-8f53-14daec4732f2.png)

**Comment by briandealwis** [comment] 2019-06-06 20:11
Is there anything in the logs?

**Comment by elharo** [comment] 2019-06-06 20:50
I think the issue may simply be that I had not added the App Engine API to the project (which the test plan does not require). However I wanted to make sure that this wasn't supposed to be found even if we don't add that library.

**Comment by briandealwis** [comment] 2019-06-07 18:45
We're not responsible for showing the quick-fix menu; we don't even populate anything there.  I'm also unable to reproduce.  Closing, but we can re-open if it happens again.

**Comment by elharo** [comment] 2019-06-07 20:02
The quick fiux menu appears, However it doesn't offer the right suggestion. The question is, should it? if it should, this is a bug. Otherwise the test plan needs to be updated.

**Comment by lak-proddev** [comment] 2019-06-09 11:27
I believe current behavior is right. 
Until the class is not in classpath the suggestion won't show. I mean, "appengine-api-1.0-sdk.jar" should be added to the classpath.

**Comment by briandealwis** [comment] 2019-06-10 14:34
Offering to add a GCP library would be a new feature: JDT doesn't offer this out of the box as it does not know how to find such jar files.  PDE offers the ability to add a bundle to the classpath by examining the bundles in the target platform.  We could add a similar Quickfix that would look to see if the class name was a known GCP library class and offer to connect that library.  This feature would require creating and shipping an index of such classes.

**Comment by elharo** [comment] 2019-06-10 15:43
Sounds like we need to update the test plan then.

**Comment by briandealwis** [comment] 2019-06-10 18:52
Did we used to add the App Engine API by default?

**Comment by elharo** [comment] 2019-06-10 20:39
Good question. I don't remember doing that, but it's possible. I'd have to dig through the git history to find out, and remind myself why we change dit, if we did.

**Comment by JoeWang1127** [comment] 2022-08-05 18:19
close as not planned

**Closed by JoeWang1127** 2022-08-05 18:19 UTC
