### ISSUE TITLE
App Engine: Could not publish to the server - java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by csivaram** [GoogleCloudPlatform/google-cloud-eclipse#3312] opened 2018-12-18 03:41 UTC
Google Cloud Tools for Eclipse Version: 1.7.1.201807071456
Google Cloud SDK: 228.0.0
Eclipse version: Oxygen.3a Release (4.7.3a)
OS: Windows 10
Java Version: 1.8.0_181

Encountered below issue while starting App Engine.
"Could not publish to the server. java.lang.IndexOutOfBoundsException"

<img width="290" alt="issue" src="https://user-images.githubusercontent.com/32742277/50130621-7443c000-02a4-11e9-8ce3-923b14e87594.png">

!ENTRY org.eclipse.core.jobs 4 2 2018-12-18 09:00:11.318
!MESSAGE An internal error occurred during: "Updating status for App Engine Standard at localhost...".
!STACK 0
java.lang.IndexOutOfBoundsException
	at java.io.BufferedInputStream.read(Unknown Source)
	at org.eclipse.jdt.internal.compiler.util.Util.getInputStreamAsByteArray(Util.java:506)
	at org.eclipse.jdt.core.ToolFactory.createDefaultClassFileReader(ToolFactory.java:311)
	at org.eclipse.jst.j2ee.internal.archive.JavaEEArchiveUtilities.isEJBArchive(JavaEEArchiveUtilities.java:913)
	at org.eclipse.jst.j2ee.internal.archive.JavaEEArchiveUtilities.refineForJavaEE(JavaEEArchiveUtilities.java:619)
	at org.eclipse.jst.j2ee.internal.archive.JavaEEArchiveUtilities.openArchive(JavaEEArchiveUtilities.java:381)
	at org.eclipse.jst.j2ee.internal.archive.JavaEEArchiveUtilities.openBinaryArchive(JavaEEArchiveUtilities.java:301)
	at org.eclipse.jst.j2ee.internal.componentcore.JavaEEBinaryComponentHelper$ArchiveCache.openArchive(JavaEEBinaryComponentHelper.java:612)
	at org.eclipse.jst.j2ee.internal.componentcore.JavaEEBinaryComponentHelper.openArchive(JavaEEBinaryComponentHelper.java:470)
	at org.eclipse.jst.j2ee.internal.componentcore.JavaEEBinaryComponentHelper.getUniqueArchive(JavaEEBinaryComponentHelper.java:422)
	at org.eclipse.jst.j2ee.internal.componentcore.JavaEEBinaryComponentHelper.getArchive(JavaEEBinaryComponentHelper.java:415)
	at org.eclipse.jst.j2ee.internal.componentcore.JavaEEBinaryComponentHelper.getJavaEEQuickPeek(JavaEEBinaryComponentHelper.java:98)
	at org.eclipse.jst.j2ee.project.JavaEEProjectUtilities.getJ2EEComponentType(JavaEEProjectUtilities.java:273)
	at org.eclipse.jst.j2ee.internal.common.exportmodel.JEEHeirarchyExportParticipant.isChildModule(JEEHeirarchyExportParticipant.java:42)
	at org.eclipse.wst.common.componentcore.internal.flat.GlobalHeirarchyParticipant.isChildModule(GlobalHeirarchyParticipant.java:41)
	at org.eclipse.wst.common.componentcore.internal.flat.FlatVirtualComponent.isChildModule(FlatVirtualComponent.java:367)
	at org.eclipse.wst.common.componentcore.internal.flat.FlatVirtualComponent.addUsedReferences(FlatVirtualComponent.java:305)
	at org.eclipse.wst.common.componentcore.internal.flat.FlatVirtualComponent.treeWalk(FlatVirtualComponent.java:235)
	at org.eclipse.wst.common.componentcore.internal.flat.FlatVirtualComponent.cacheResources(FlatVirtualComponent.java:188)
	at org.eclipse.wst.common.componentcore.internal.flat.FlatVirtualComponent.fetchResources(FlatVirtualComponent.java:118)
	at org.eclipse.wst.web.internal.deployables.FlatComponentDeployable.members(FlatComponentDeployable.java:227)
	at org.eclipse.jst.j2ee.internal.deployables.J2EEFlexProjDeployable.members(J2EEFlexProjDeployable.java:267)
	at org.eclipse.wst.server.core.internal.ModulePublishInfo.fillCache(ModulePublishInfo.java:314)
	at org.eclipse.wst.server.core.internal.ModulePublishInfo.hasDelta(ModulePublishInfo.java:424)
	at org.eclipse.wst.server.core.internal.ServerPublishInfo.hasDelta(ServerPublishInfo.java:440)
	at org.eclipse.wst.server.core.internal.Server.hasPublishedResourceDelta(Server.java:1600)
	at org.eclipse.wst.server.core.internal.Server$ResourceChangeJob$1.visit(Server.java:217)
	at org.eclipse.wst.server.core.internal.Server.visitModule(Server.java:3065)
	at org.eclipse.wst.server.core.internal.Server.visit(Server.java:3049)
	at org.eclipse.wst.server.core.internal.Server$ResourceChangeJob.run(Server.java:233)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)

**Comment by elharo** [comment] 2018-12-18 11:54
I don't immediately see the cause of the problem, but Oxygen is getting a little old. Maybe try upgrading to Photon or later and see if it still happens?

**Comment by chanseokoh** [comment] 2018-12-18 13:40
Looks like a duplicate of #3193.

**Comment by JoeWang1127** [comment] 2022-08-05 18:15
close as not planned

**Closed by JoeWang1127** 2022-08-05 18:15 UTC
