### ISSUE TITLE
An internal error occurred during: "Requesting Java AST from selection". 'boolean com.ibm.icu.text.UTF16.isSurrogate(char)'

### ISSUE THREAD

**Issue by craigdetter** [GoogleCloudPlatform/google-cloud-eclipse#3704] opened 2022-12-14 22:35 UTC
- Cloud Tools for Eclipse version: 1.9.1.202211291623
- Google Cloud SDK version: 409.0.0 (non-managed)
- Eclipse version: 4.21.0.v20210906-0500
- OS: Mac OS X 10.16
- Java version: 16.0.2

**What did you do?**
Open Eclipse in 2021-09 (latest supported version per Google)
https://marketplace.eclipse.org/content/google-cloud-tools-eclipse

**What did you expect to see?**
No error messages

**What did you see instead?**
An internal error occurred during: "Requesting Java AST from selection".
'boolean com.ibm.icu.text.UTF16.isSurrogate(char)'

Tried restarting Eclipse, no change.

**Comment by diegomarquezp** [comment] 2022-12-19 21:48
Hello @craigdetter. We could not replicate with the given specifications. According to [this SO](https://stackoverflow.com/questions/74751823/an-internal-error-occurred-during-requesting-java-ast-from-selection-boolea), it could be that there is another plugin producing this failure. The thread confirmed a fix by updating some plugins. Hope that works.

**Comment by diegomarquezp** [comment] 2022-12-19 23:41
Reopened as confirmed when opening an AppEngine project both in 1.8.5 and 1.9.1

**Comment by meltsufin** [comment] 2022-12-20 01:58
[This SO thread](https://stackoverflow.com/questions/74780857/boolean-com-ibm-icu-text-utf16-issurrogatechar) helped me resolve the issue by disabling "mark occurrences".

**Comment by diegomarquezp** [comment] 2023-03-27 16:01
Closing since there is a workaround

**Closed by diegomarquezp** 2023-03-27 16:01 UTC
Labels: type: bug, p2
