### ISSUE TITLE
I can't create a Google App Engine Standard Java Project

### ISSUE THREAD

**Issue by TimothySonofSam** [GoogleCloudPlatform/google-cloud-eclipse#3667] opened 2022-01-24 15:30 UTC
Every time I try to create one of these projects, I get this error thrown at me:

```
!project.creation.failed!: Cannot invoke "com.google.cloud.tools.eclipse.appengine.libraries.persistence.LibraryClasspathContainerSerializer.loadContainer(org.eclipse.jdt.core.IJavaProject, org.eclipse.core.runtime.IPath)" because "this.serializer" is null
Cannot invoke "com.google.cloud.tools.eclipse.appengine.libraries.persistence.LibraryClasspathContainerSerializer.loadContainer(org.eclipse.jdt.core.IJavaProject, org.eclipse.core.runtime.IPath)" because "this.serializer" is null
```

I don't understand what it means and nothing online is helping me figure out what went wrong. I followed a full 15 minute tutorial on YouTube for setting up the Google Cloud Eclipse plug-in to the letter and it's still not working for me. Please somebody help me understand what happened and why I can't create a project because my senior project depends on me being able to do this.

**Comment by elharo** [comment] 2022-01-24 15:36
Best guess 9and only a guess): you're using amore recent version of Eclipse than the plugin supports.

**Comment by mpeddada1** [comment] 2022-01-25 00:01
Thanks for filing the issue @TimothySonofSam and the answer @elharo. Yes, please verify the version of Eclipse and the plugin you're using.

**Comment by vontab** [comment] 2022-01-26 14:54
I've been fighting with the same issue for a few day. I downloaded latest Eclipse 21-12 and installed google cloud tools. I've created new Windows server and started from fresh, but every attempt gives: 
Caused by: java.lang.NullPointerException
	at com.google.cloud.tools.eclipse.appengine.libraries.LibraryClasspathContainerInitializer.initialize(LibraryClasspathContainerInitializer.java:76)
	at org.eclipse.jdt.internal.core.JavaModelManager.initializeContainer(JavaModelManager.java:3144)
	at org.eclipse.jdt.internal.core.JavaModelManager.getClasspathContainer(JavaModelManager.java:2092)
	at org.eclipse.jdt.core.JavaCore.getClasspathContainer(JavaCore.java:3783)
	at org.eclipse.jdt.internal.ui.wizards.buildpaths.CPListElement.create(CPListElement.java:721)

**Comment by elharo** [comment] 2022-01-26 14:58
The latest eclipse is likely your problem. Try an older one. What was current about two years ago probably works. 

If you have a support contract with Google Cloud,  it would help if file a support request for this through the contracted channels.

**Comment by vontab** [comment] 2022-01-26 15:15
It works well with 21-09, so you're right that 2021-12 is not supported.

**Comment by TimothySonofSam** [comment] 2022-01-26 16:06
I downloaded the older version and it works now! Thank you for your help.

**Comment by elharo** [comment] 2022-01-26 17:17
Thanks for the info. Let me see if I still have permissions to update this in the Eclipse store.

**Comment by elharo** [comment] 2022-01-26 17:21
Looks like I don't. @briandealwis  can you update https://marketplace.eclipse.org/node/3321165 to set 2021-09 as the max supported version?

**Comment by elharo** [comment] 2022-01-26 17:27
OK, figured it out. The marketplace now shows 4.21/2021-09 as the last supported version, at least until we can release a new version of the plugin.

**Comment by vbresan** [comment] 2022-02-12 10:25
Is there any idea when that might happen?

**Comment by elharo** [comment] 2022-02-14 13:23
If you have a support contract with Google Cloud, please file a support request for this through the contracted channels.

**Comment by diego92sigma6** [comment] 2022-08-08 18:50
Closing as solved

**Closed by diego92sigma6** 2022-08-08 18:50 UTC
Labels: App Engine Standard, p3
