### ISSUE TITLE
Expired Auth after signin? 

### ISSUE THREAD

**Issue by arouzrokh** [GoogleCloudPlatform/google-cloud-eclipse#1092] opened 2016-12-09 19:52 UTC
How long does the sign in last in eclipse? I got this when I logged back in a few days later into eclipse:

```
********************************************************
There is a new version of the SDK available.
-----------
Latest SDK:
Release: 1.9.48
Timestamp: Wed Oct 26 16:44:58 EDT 2016
API versions: [1.0]

-----------
Your SDK:
Release: 1.9.46
Timestamp: Tue Oct 18 21:22:06 EDT 2016
API versions: [1.0]

-----------
Please visit https://developers.google.com/appengine/downloads for the latest SDK.
********************************************************
Reading application configuration data...


Beginning interaction for module default...
Success.
Temporary staging for module default directory left in /Users/arouzrokh/Documents/CT4E/.metadata/.plugins/com.google.cloud.tools.eclipse.appengine.deploy/tmp/1481214382674/staging
You are about to deploy the following services:
 - eclipsesample-151702/default/flex (from [/Users/arouzrokh/Documents/CT4E/.metadata/.plugins/com.google.cloud.tools.eclipse.appengine.deploy/tmp/1481214382674/staging/app.yaml])
     Deploying to URL: [https://eclipsesample-151702.appspot.com]

If this is your first deployment, this may take a while.....................................................................................failed.

WARNING: We couldn't validate that your project is ready to deploy to App Engine Flexible Environment. If deployment fails, please check the following message and try again:

Server responded with code [401]:
  Unauthorized Too many auth attempts..
  Invalid OAuth token

Beginning deployment of service [default]...
WARNING: Deployment of App Engine Flexible Environment apps is currently in Beta
WARNING: Could not generate [source-context.json]: Could not list remote URLs from source directory: /Users/arouzrokh/Documents/CT4E/.metadata/.plugins/com.google.cloud.tools.eclipse.appengine.deploy/tmp/1481214382674/staging
Building and pushing image for service [default]
ERROR: (gcloud.app.deploy) You do not have permission to access project [eclipsesample-151702] (or it may not exist): Google Cloud Container Builder API has not been used in project cloud-tools-for-eclipse before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/cloudbuild.googleapis.com/overview?project=cloud-tools-for-eclipse then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
```

when trying to deploy. I think you may need to refresh the token no? Please consider this case and generate proper errors if possible.

**Comment by chanseokoh** [comment] 2016-12-09 20:04
Interesting. (I thought it never expires since we only pass a refresh token, but there may be something else.) Can you check if this is reproducible? For other projects as well? And after that, can try again after signing out and in back?

**Comment by diegomarquezp** [comment] 2024-11-21 17:03
Closing as not planned.

**Closed by diegomarquezp** 2024-11-21 17:03 UTC
Labels: type: bug, p4, priority: p4
