### ISSUE TITLE
Problem install SDK while deploy project with gcloud under eclipse

### ISSUE THREAD

**Issue by Patrick-Petit** [GoogleCloudPlatform/google-cloud-eclipse#2948] opened 2018-03-15 21:02 UTC
- Cloud Tools for Eclipse version: 1.6.0.201803071812
- Google Cloud SDK version: 193.0.0
- Eclipse version: 4.7.2.v20171130-0510
- OS: Windows 10 10.0
- Java version: 1.8.0_162

I have create project standard Java when i deploy  a message error:
Deploy failed: cannot install Google Cloud SDK
Failed to install the Google Cloud SDK.
Process failed with exit code: 1

any ideas

**Comment by chanseokoh** [comment] 2018-03-15 21:05
Duplicate of #2949. Closing.

**Closed by chanseokoh** 2018-03-15 21:05 UTC
