### ISSUE TITLE
Adding libraries to native projects clears previously added libraries

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#2490] opened 2017-10-13 18:06 UTC
This is at HEAD. To reproduce

1. Create a plain Java project.
1. _Build Path_ > _Add Libraries..._> _App Engine Libraries_ > _Endpoints_. Close.
    - You'll see a lot of JARs in the _Google APIs_ library container.
1. _Build Path_ > _Add Libraries..._> _App Engine Libraries_ > _Objectify_. Close.

Check _Google APIs_. Endpoints is gone.

**Comment by briandealwis** [comment] 2017-10-13 18:59
This is kind of a dupe of #2400.

**Comment by elharo** [comment] 2017-10-13 18:59
I think this happened in #2436 when we started creating a new master library in BuildPath instead of pulling one from the cache.

**Comment by elharo** [comment] 2017-10-13 19:01
I was hoping we didn't have to solve #2400 right now. Since we have two different lists of libraries that would be tricky.

**Comment by briandealwis** [comment] 2017-10-13 19:02
@chanseokoh Could you expand exactly on:

> 2. Add Cloud Datastore

I'm guessing this was _Properties > Java Build Path > Add Library_?  Or something else?

**Comment by elharo** [comment] 2017-10-13 19:05
Yes, adding two at a time is fine. The problem is new entries overwrite all old entries. 

It's a hack but maybe we can just call `LibraryClasspathContainerSerializer.loadLibraryIds` to get the list of previously chosen IDs.

**Comment by chanseokoh** [comment] 2017-10-13 19:09
> I'm guessing this was _Properties > Java Build Path > Add Library_?

Yes.

**Closed** 2017-10-14 18:16 UTC
Labels: bug, high priority
