### ISSUE TITLE
com.google.cloud.tools.eclipse.appengine.localserver.ui.LocalAppEngineConsole cannot be cast to org.eclipse.jdt.internal.debug.ui.console.JavaStackTraceConsole

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#2220] opened 2017-08-02 16:05 UTC
While running the local server on a standard Java 7 project:

```
The following will be send to: Eclipse


REPORT

anonymousId         aae796b1-5728-426b-bc5d-2545e3673b0e
name                
email               
comment             
eclipseBuildId      4.6.3.M20170301-0400
eclipseProduct      org.eclipse.epp.package.jee.product
javaRuntimeVersion  1.8.0_131-b11
osgiWs              cocoa
osgiOs              MacOSX
osgiOsVersion       10.12.6
osgiArch            x86_64
severity            UNKNOWN


STATUS

pluginId            org.eclipse.ui.console
pluginVersion       3.6.201.v20161107-0337
code                2
severity            4
message             Problems occurred when invoking code from plug-in: "org.eclipse.ui.console".
fingerprint         ec07297d7d373342ce90a3b922baeca9

Exception:java.lang.ClassCastException: com.google.cloud.tools.eclipse.appengine.localserver.ui.LocalAppEngineConsole cannot be cast to org.eclipse.jdt.internal.debug.ui.console.JavaStackTraceConsole
	 at org.eclipse.jdt.internal.debug.ui.console.JavaStackTracePageParticipant.init(JavaStackTracePageParticipant.java:50)
	 at org.eclipse.ui.internal.console.ConsoleView$3.run(ConsoleView.java:326)
	 at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	 at org.eclipse.ui.internal.console.ConsoleView.doCreatePage(ConsoleView.java:323)
	 at org.eclipse.ui.part.PageBookView.createPage(PageBookView.java:400)
	 at org.eclipse.ui.part.PageBookView.partActivated(PageBookView.java:743)
	 at org.eclipse.ui.internal.console.ConsoleView$4.run(ConsoleView.java:395)
	 at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	 at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
	 at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4032)
	 at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3708)
	 at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
	 at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	 at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	 at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
	 at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:693)
	 at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	 at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:610)
	 at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	 at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)
	 at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	 at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	 at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	 at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	 at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	 at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
	 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	 at java.lang.reflect.Method.invoke(Method.java:498)
	 at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	 at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	 at org.eclipse.equinox.launcher.Main.run(Main.java:1519)


BUNDLES

name                org.eclipse.core.databinding.observable
version             1.6.0.v20160511-1747

name                org.eclipse.core.databinding
version             1.6.0.v20160412-0910

name                org.eclipse.core.runtime
version             3.12.0.v20160606-1342

name                org.eclipse.e4.ui.workbench
version             1.4.0.v20160517-1624

name                org.eclipse.e4.ui.workbench.swt
version             0.14.1.v20160829-0832

name                org.eclipse.equinox.app
version             1.3.400.v20150715-1528

name                org.eclipse.equinox.launcher
version             1.3.201.v20161025-1711

name                org.eclipse.jdt.debug.ui
version             3.7.201.v20160811-0450

name                org.eclipse.jdt.debug
version             3.10.1.v20160811-0441

name                org.eclipse.jdt
version             3.12.3.v20170301-0400

name                org.eclipse.swt
version             3.105.3.v20170228-0512

name                org.eclipse.ui
version             3.108.1.v20160929-1045

name                org.eclipse.ui.console
version             3.6.201.v20161107-0337

name                org.eclipse.ui.ide.application
version             1.1.101.v20160829-0827

name                org.eclipse.ui.ide
version             3.12.3.v20170119-0935

```

**Comment by chanseokoh** [comment] 2017-08-02 17:14
Duplicate of #2150.

**Closed by chanseokoh** 2017-08-02 17:14 UTC
Labels: bug

**Comment by briandealwis** [comment] 2017-08-02 19:44
Oh dear, I didn't think of this triggering AERI.  That ups the priority of #2150.
