### ISSUE TITLE
service name off by one when reading name out of wizard

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1830] opened 2017-04-19 17:39 UTC
E.g. try to deploy a service "silver" and what's actually deployed is "silve".

Deploy "123" and what's deployed is "123" and so forth. 

Possibly only in projects created with standard wizard. Problem happens before deployment in service element written to appengine-web.xml:

```
  <service>silver12</service>
```

**Comment by elharo** [comment] 2017-04-19 18:05
Problem is in the wizard dialog. As soon as you click **Finish** the last letter in the Service field is cut off.  If you watch closely, you can see it happen.

![image](https://cloud.githubusercontent.com/assets/1005544/25194693/46c7a666-2509-11e7-921f-5994d6c108e5.png)

**Comment by elharo** [comment] 2017-04-19 18:16
From the debugger this is happening very early, when we call

```
  public String getServiceName() {
    String text = serviceNameField.getText();
    return text;
  }
```
or sooner. Almost looks like an Eclipse bug.

**Comment by briandealwis** [comment] 2017-04-20 16:04
I've been poking at this too.  I'm flummoxed.
  - **good news**: this only seems to happen in the debugger — I can't reproduce with CT4E 1.0.3.201704111618 in my IDE
  - **it continues to happen when I switch the order of creation with the package field**
  - unrelated to the page-validator/modify listener (continues if I don't install the Text's modify listener)
  - unrelated to the use of `Text#setMessage()`
  - only happens if the service field has focus
  - it's triggered by the call within the wizard to `getContainer().run()`; if I skip that it's ok
     - tracing through `getContainer().run()`, past `ModalContext#block()` and into `Display#readAndDispatch()`, the change happens on the first call at:

        NSEvent event = application.nextEventMatchingMask(0, null, OS.NSDefaultRunLoopMode, true);

**Comment by briandealwis** [comment] 2017-04-20 16:10
If I retrieve the value in `validateLocalFields()`, it's ok.  Incidentally, turns out that we're not actually performing service name validation.

**Comment by briandealwis** [comment] 2017-04-20 18:20
I've been able to reproduce with a small standalone example outside of the debugger.  I've [filed a bug against SWT](https://bugs.eclipse.org/bugs/show_bug.cgi?id=515541).

**Comment by elharo** [comment] 2017-04-20 18:31
FWIW I initially found this outside the debugger in Oxygen M6 with 1.0.3 installed.

**Comment by briandealwis** [comment] 2017-04-20 18:49
I've since reproduced in my install too.  I suspect I must have changed the focus to another field when testing.

**Comment by briandealwis** [comment] 2017-08-09 20:47
Removed high-priority and closing since we have workarounds.

**Closed by briandealwis** 2017-08-09 20:47 UTC
Labels: bug
