### ISSUE TITLE
dataflow version is empty

### ISSUE THREAD

**Issue by repl-abhishek-srivastava** [GoogleCloudPlatform/google-cloud-eclipse#3585] opened 2019-12-18 13:52 UTC
- Cloud Tools for Eclipse version: 1.8.3.201912102258
- Google Cloud SDK version: 266.0.0 (non-managed)
- Eclipse version: 4.13.0.v20190916-1045
- OS: Windows 10 10.0
- Java version: 1.8.0_231

**What did you do?**

**What did you expect to see?**

**What did you see instead?**

**Comment by elharo** [comment] 2019-12-18 13:59
do you have a screenshot by any chance?

**Comment by repl-abhishek-srivastava** [comment] 2019-12-18 14:02
Please find the screenshot attached. There is no value in drop down for
dataflow version.

[image: image.png]

*Abhishek Srivastava* | Data Warehouse Engineer | Direct Phone
1-650-670-3081 | Internal ext. 7141

*Replicon* | The Time IntelligenceTM Company - 7,800+ Customers - 70+
Countries - 1.5 Million Users
www.replicon.com | Time Intelligence
<https://www.replicon.com/time-intelligence/>TM | facebook
<http://www.facebook.com/Replicon.inc> | linkedin
<http://www.linkedin.com/company/27961?trk=tyah> | twitter
<http://twitter.com/Replicon> | blog <http://www.replicon.com/blog/> | contact
us <http://www.replicon.com/contact-us>

*We are hiring!* | search jobs <http://www.replicon.com/careers>

**Comment by elharo** [comment] 2019-12-18 14:15
I think I know what you mean but the screenshot did not attach. I can't reproduce this yet.

**Comment by repl-abhishek-srivastava** [comment] 2019-12-18 14:31
Please find the screenshot attached.

[image: image.png]


*Abhishek Srivastava* | Data Warehouse Engineer | Direct Phone
1-650-670-3081 | Internal ext. 7141

*Replicon* | The Time IntelligenceTM Company - 7,800+ Customers - 70+
Countries - 1.5 Million Users
www.replicon.com | Time Intelligence
<https://www.replicon.com/time-intelligence/>TM | facebook
<http://www.facebook.com/Replicon.inc> | linkedin
<http://www.linkedin.com/company/27961?trk=tyah> | twitter
<http://twitter.com/Replicon> | blog <http://www.replicon.com/blog/> | contact
us <http://www.replicon.com/contact-us>

*We are hiring!* | search jobs <http://www.replicon.com/careers>

**Comment by repl-abhishek-srivastava** [comment] 2019-12-18 14:32
I guess this will be helpful.
There is no value for dataflow version when I am selecting the dropdown
list.

*Abhishek Srivastava* | Data Warehouse Engineer | Direct Phone
1-650-670-3081 | Internal ext. 7141

*Replicon* | The Time IntelligenceTM Company - 7,800+ Customers - 70+
Countries - 1.5 Million Users
www.replicon.com | Time Intelligence
<https://www.replicon.com/time-intelligence/>TM | facebook
<http://www.facebook.com/Replicon.inc> | linkedin
<http://www.linkedin.com/company/27961?trk=tyah> | twitter
<http://twitter.com/Replicon> | blog <http://www.replicon.com/blog/> | contact
us <http://www.replicon.com/contact-us>

*We are hiring!* | search jobs <http://www.replicon.com/careers>

**Comment by elharo** [comment] 2019-12-18 14:58
Image still not coming through. Looks like you might be emailing. Try logging into github and editing it there instead.

**Comment by repl-abhishek-srivastava** [comment] 2019-12-18 15:11
![dataflow](https://user-images.githubusercontent.com/45486264/71097887-ca5c8380-21d6-11ea-80a0-22766df33774.png)

**Comment by elharo** [comment] 2019-12-18 16:17
OK, that's pretty much what I thought you saw. Until we can reproduce and fix that, try typing 2.5.0 into that field as a workaround.

**Comment by repl-abhishek-srivastava** [comment] 2019-12-18 16:52
I tried the same. I wrote 2.5.0 then I got the error:

Error encountered when trying to create project: Could not resolve archetype com.google.cloud.dataflow:google-cloud-dataflow-java-archetypes-starter:2.5.0 from any of the configured repositories.
Could not resolve archetype com.google.cloud.dataflow:google-cloud-dataflow-java-archetypes-starter:2.5.0 from any of the configured repositories.
Could not resolve artifact com.google.cloud.dataflow:google-cloud-dataflow-java-archetypes-starter:pom:2.5.0
Failure to transfer com.google.cloud.dataflow:google-cloud-dataflow-java-archetypes-starter:pom:2.5.0 from https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced. Original error: Could not transfer artifact com.google.cloud.dataflow:google-cloud-dataflow-java-archetypes-starter:pom:2.5.0 from/to central (https://repo.maven.apache.org/maven2): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
Failure to transfer com.google.cloud.dataflow:google-cloud-dataflow-java-archetypes-starter:pom:2.5.0 from https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced. Original error: Could not transfer artifact com.google.cloud.dataflow:google-cloud-dataflow-java-archetypes-starter:pom:2.5.0 from/to central (https://repo.maven.apache.org/maven2): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by chanseokoh** [comment] 2019-12-18 17:19
This seems like an issue specific to your environment. Particularly a TLS/SSL certification issue.

> PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

I bet the following command will fail as well.
```
$ mvn archetype:generate \
  -DgroupId=com.example \
  -DartifactId=my-app \
  -DarchetypeGroupId=com.google.cloud.dataflow \
  -DarchetypeArtifactId=google-cloud-dataflow-java-archetypes-starter \
  -DarchetypeVersion=2.5.0 \
  -DinteractiveMode=false \
  -U
```

It is not clear which server you cannot verify in your environment, but I think it's very well possible that even accessing `https://repo.maven.apache.org/` may fail. Try below and see if they also fail.

```
$ curl https://repo.maven.apache.org/maven2/com/google/cloud/dataflow/google-cloud-dataflow-java-archetypes-parent/2.5.0/google-cloud-dataflow-java-archetypes-parent-2.5.0.pom

$ curl https://repo.maven.apache.org/
```

**Comment by repl-abhishek-srivastava** [comment] 2019-12-18 17:23
can you please tell me how to resolve this issue

**Comment by chanseokoh** [comment] 2019-12-18 17:25
Contact your network administrator and tell them your machine cannot access https://repo.maven.apache.org/ over HTTPS due to certification failure. They should know better about this. The URL should just work. Maybe it will also fail when you access https://repo.maven.apache.org/ using a browser on your machine.

**Comment by repl-abhishek-srivastava** [comment] 2019-12-18 17:37
![output](https://user-images.githubusercontent.com/45486264/71109412-23cead80-21eb-11ea-985b-cd56560a5cd5.PNG)

I am getting this as output

**Comment by elharo** [comment] 2019-12-18 17:54
That's all true, but we should have a better fallback and error dialog here when this happens. We might be swallowing an IOException somewhere.

**Comment by repl-abhishek-srivastava** [comment] 2019-12-18 17:59
I am attaching the error screenshot. I am able to browse the above mention link.
![error](https://user-images.githubusercontent.com/45486264/71110928-43b3a080-21ee-11ea-9327-3ea939dd515a.PNG)

**Comment by chanseokoh** [comment] 2019-12-18 18:09
Actually, a browser may work different about this. What's the result of running below on the command line?

```
$ mvn archetype:generate \
  -DgroupId=com.example \
  -DartifactId=my-app \
  -DarchetypeGroupId=com.google.cloud.dataflow \
  -DarchetypeArtifactId=google-cloud-dataflow-java-archetypes-starter \
  -DarchetypeVersion=2.5.0 \
  -DinteractiveMode=false \
  -U

$ curl https://repo.maven.apache.org/maven2/com/google/cloud/dataflow/google-cloud-dataflow-java-archetypes-parent/2.5.0/google-cloud-dataflow-java-archetypes-parent-2.5.0.pom

$ curl https://repo.maven.apache.org/
```

**Comment by repl-abhishek-srivastava** [comment] 2019-12-18 18:12
I got this
![cmd_error](https://user-images.githubusercontent.com/45486264/71111717-ffc19b00-21ef-11ea-8a2d-fdeca6237f70.PNG)

**Comment by chanseokoh** [comment] 2019-12-18 18:15
What about 

```
$ curl https://repo.maven.apache.org/maven2/com/google/cloud/dataflow/google-cloud-dataflow-java-archetypes-parent/2.5.0/google-cloud-dataflow-java-archetypes-parent-2.5.0.pom

$ curl https://repo.maven.apache.org/
```
?

**Comment by repl-abhishek-srivastava** [comment] 2019-12-18 18:19
![error1](https://user-images.githubusercontent.com/45486264/71112168-f684fe00-21f0-11ea-801d-cf4193bad6fc.PNG)

**Comment by chanseokoh** [comment] 2019-12-18 18:26
That's interesting. It could be that Maven is configured to be behind a proxy. What's the result of `mvn help:effective-settings`? (Remove any sensitive output.)

**Comment by repl-abhishek-srivastava** [comment] 2019-12-18 18:41
![erro2](https://user-images.githubusercontent.com/45486264/71113667-1538c400-21f4-11ea-9781-a9c1188d38c8.PNG)

**Comment by chanseokoh** [comment] 2019-12-18 18:48
As I expected. See the answers in https://stackoverflow.com/a/25912982 and try to fix the problem. It must be a certificate issue.

**Comment by chanseokoh** [comment] 2019-12-18 18:53
If you still have trouble getting it fixed yourself, contact your network administrator for some help. Perhaps some expert knowledgeable of Java (Maven actually), network, proxies, and particularly TLS/SSL certificate verification.

**Comment by repl-abhishek-srivastava** [comment] 2019-12-18 19:03
I got a certificate from my admin, can you please tell me where I should put this.
May be it sounds funny , but I am actually pretty new for this

**Comment by repl-abhishek-srivastava** [comment] 2019-12-19 12:52
I downloaded the certificate and import as its destination but still getting the same error.

**Comment by repl-abhishek-srivastava** [comment] 2019-12-19 14:17
We have our CA certificate. How do i import or use that in google cloud SDK /  Google cloud SDK plugin on Eclipse.

**Comment by repl-abhishek-srivastava** [comment] 2019-12-19 14:17
And I am using windows operating system.

**Comment by repl-abhishek-srivastava** [comment] 2019-12-19 14:29
> As I expected. See the answers in https://stackoverflow.com/a/25912982 and try to fix the problem. It must be a certificate issue.

I have the ca certificate, how do i import in to this sdk to work.

**Comment by diego92sigma6** [comment] 2022-08-02 18:08
Closing as part of cleanup. Please re-open if it's still relevant

**Closed** 2022-08-02 18:08 UTC
Labels: bug
