### ISSUE TITLE
Are we compatible with Android?

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1544] opened 2017-03-07 19:52 UTC
Here's an install error that showed up in the marketplace. Possibly some holdover from the android parts of GPE where we need an extra exclusion?

Error Code: 
4
Error Message: 

Operation details
Installable Units Reported: 
com.google.cloud.tools.eclipse.suite.e45.feature.feature.group,1.0.0.201702221633
Detailed Message: 
Cannot complete the install because some dependencies are not satisfiable Software being installed: Google Cloud Platform for Eclipse 4.5 and later 1.0.0.201702221633 (com.google.cloud.tools.eclipse.suite.e45.feature.feature.group 1.0.0.201702221633) Software currently installed: Google App Engine Tools for Android 3.8.0.v201410302155-rel-r43 (com.google.gdt.eclipse.mobile.android.feature.feature.group 3.8.0.v201410302155-rel-r43) Cannot satisfy dependency: From: Google Cloud Platform for Eclipse 4.5 and later 1.0.0.201702221633 (com.google.cloud.tools.eclipse.suite.e45.feature.feature.group 1.0.0.201702221633) To: com.google.gdt.eclipse.mobile.android.feature.feature.group 0.0.0

**Comment by briandealwis** [comment] 2017-03-09 18:55
Caused by our anti-GPE p2 negative prereq from #1075.  We could back out the negs specific to the android tooling.

**Comment by elharo** [comment] 2017-03-09 20:42
I don't know that we want to do that, but shouldn't an install of CT4E cause an uninstall of GPE? Or is this reported even if the user cancels because they don't want to uninstall GPE? in which case it's WAI.

**Comment by briandealwis** [comment] 2017-03-13 19:07
This error may be reported back before the p2 conflict-resolution screen is shown?  Or perhaps its shown if they decide to refuse the conflict resolution?

**Comment by briandealwis** [comment] 2017-03-29 16:16
Fixed by #1683

**Closed by briandealwis** 2017-03-29 16:16 UTC
Labels: build
