### ISSUE TITLE
Couldn't create a Google App Engine Project.

### ISSUE THREAD

**Issue by ilias-y** [GoogleCloudPlatform/google-cloud-eclipse#2055] opened 2017-06-13 12:36 UTC
I installed the GAE from a eclipse marketplace and I set the config with google-cloud-sdk. I could make a project with 'Google App Engine Standard Java Project' but couldn't make 'a project with 'Maven-based Google App Engine Standard Java Project'. 
Here is error log.
![image](https://user-images.githubusercontent.com/29403038/27082544-3034fcc6-5080-11e7-81fd-ff625613acd7.png)

How to configure Java8,  CloudSDK_Tooling and service(what is it?)?

**Comment by chanseokoh** [comment] 2017-06-13 13:56
Hi,

This is a duplicate of #2011. The fix is in version 1.2.0, which went out just yesterday. I believe the version you are using is below 1.2.0. Please upgrade our plugin and try again.

**Comment by chanseokoh** [comment] 2017-06-13 13:58
Feel free to reopen if you still have problems. Thanks!

**Closed by chanseokoh** 2017-06-13 13:58 UTC

**Comment by ilias-y** [comment] 2017-06-13 14:14
Hi, my version are

# gcloud -v
Google Cloud SDK 158.0.0
app-engine-java 1.9.53
app-engine-python 1.9.54
bq 2.0.24
core 2017.06.02
gcloud 
gsutil 4.26

I just update app-engine-java with gcloud command and got same error. what is the plugin you said?

**Comment by chanseokoh** [comment] 2017-06-13 14:16
I am talking about our Google Cloud Tools for Eclipse (CT4E) plugin. Try checking if new updates are available inside Eclipse.

**Comment by ilias-y** [comment] 2017-06-13 14:22
Thank you for fast answer!
