### ISSUE TITLE
"OperationalError: database is locked" during server startup

### ISSUE THREAD

**Issue by NicolaSpreafico** [GoogleCloudPlatform/google-cloud-eclipse#596] opened 2016-08-22 06:55 UTC
Hello,

I'm getting the following stack during the server startup

```
ERROR    2016-08-22 08:50:21,934 module.py:874] Request to '/_ah/warmup' failed
INFO     2016-08-22 08:50:21,934 module.py:788] default: "GET /_ah/warmup HTTP/1.1" 500 -
FATAL ERROR in native method: JDWP No transports initialized, jvmtiError=AGENT_ERROR_TRANSPORT_INIT(197)
ERROR: transport error 202: connect failed: Connection refused
ERROR: JDWP Transport dt_socket failed to initialize, TRANSPORT_INIT(510)
ERROR    2016-08-22 08:50:39,625 http_runtime.py:396] bad runtime process port ['']
JDWP exit error AGENT_ERROR_TRANSPORT_INIT(197): No transports initialized [debugInit.c:750]
ERROR    2016-08-22 08:50:39,726 http_proxy.py:116] bad runtime process port ['']
INFO     2016-08-22 08:50:41,831 devappserver2.py:769] Skipping SDK update check.
INFO     2016-08-22 08:50:41,849 module.py:402] [default] Detected file changes:
  WEB-INF\appengine-generated\queue.yaml
INFO     2016-08-22 08:50:42,016 api_server.py:205] Starting API server at: http://localhost:59775
INFO     2016-08-22 08:50:42,395 dispatcher.py:197] Starting module "default" running at: http://localhost:8080
INFO     2016-08-22 08:50:42,397 admin_server.py:116] Starting admin server at: http://localhost:8000
FATAL ERROR in native method: JDWP No transports initialized, jvmtiError=AGENT_ERROR_TRANSPORT_INIT(197)
ERROR: transport error 202: connect failed: Connection refused
ERROR: JDWP Transport dt_socket failed to initialize, TRANSPORT_INIT(510)
ERROR    2016-08-22 08:50:43,767 http_runtime.py:396] bad runtime process port ['']
JDWP exit error AGENT_ERROR_TRANSPORT_INIT(197): No transports initialized [debugInit.c:750]
ERROR    2016-08-22 08:50:44,888 module.py:874] Request to '/_ah/warmup' failed
ago 22, 2016 8:50:43 AM com.google.appengine.tools.development.SystemPropertiesManager setSystemProperties

INFORMAZIONI: Overwriting system property key 'java.util.logging.config.file', value 'C:\Program Files\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\tools\java\config\sdk\logging.properties' with value 'WEB-INF/logging.properties' from 'C:\Users\Nicola\workspace_neon\.metadata\.plugins\org.eclipse.wst.server.core\tmp0\fastweb-rivenditori-be\WEB-INF\appengine-web.xml'

ago 22, 2016 6:50:43 AM com.google.appengine.tools.development.AbstractContainerService configure

AVVERTENZA: Null value for containerConfigProperties.get(devappserver.portMappingProvider)

ago 22, 2016 6:50:43 AM com.google.apphosting.utils.jetty.JettyLogger info

INFORMAZIONI: Logging to JettyLogger(null) via com.google.apphosting.utils.jetty.JettyLogger

ago 22, 2016 6:50:46 AM com.google.apphosting.utils.jetty.JettyLogger info

INFORMAZIONI: jetty-6.1.x

ago 22, 2016 6:50:46 AM com.google.apphosting.utils.jetty.JettyLogger info

INFORMAZIONI: Started SelectChannelConnector@localhost:59777

ago 22, 2016 6:50:46 AM com.google.appengine.tools.development.AbstractModule startup

INFORMAZIONI: Module instance default is running at http://localhost:59777/

ago 22, 2016 6:50:46 AM com.google.appengine.tools.development.AbstractModule startup

INFORMAZIONI: The admin console is running at http://localhost:59777/_ah/admin

ago 22, 2016 6:50:46 AM com.google.appengine.tools.development.devappserver2.DevAppServer2Impl doStart

INFORMAZIONI: Dev App Server is now running

ERROR    2016-08-22 08:50:49,944 module.py:1375] Internal error while handling warmup request.
Traceback (most recent call last):
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\tools\devappserver2\module.py", line 1371, in _warmup
    request_type=instance.READY_REQUEST)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\tools\devappserver2\module.py", line 760, in _handle_request
    module=self._module_configuration.module_name)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\api\apiproxy_stub.py", line 166, in WrappedMethod
    return method(self, *args, **kwargs)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\api\logservice\logservice_stub.py", line 172, in start_request
    host, start_time, method, resource, http_version, module))
OperationalError: database is locked
INFO     2016-08-22 08:50:49,944 module.py:788] default: "GET /_ah/warmup HTTP/1.1" 500 -
ERROR    2016-08-22 08:50:53,374 module.py:1375] Internal error while handling warmup request.
Traceback (most recent call last):
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\tools\devappserver2\module.py", line 1371, in _warmup
    request_type=instance.READY_REQUEST)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\tools\devappserver2\module.py", line 760, in _handle_request
    module=self._module_configuration.module_name)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\api\apiproxy_stub.py", line 166, in WrappedMethod
    return method(self, *args, **kwargs)
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\api\logservice\logservice_stub.py", line 172, in start_request
    host, start_time, method, resource, http_version, module))
OperationalError: database is locked
```

Is it only a warning of there is an effective problem on my configuration?

I think that the boot logs are more verbose compared to the previous plugin, I do not have all this messages, or simply they are just hidden.

**Comment by briandealwis** [comment] 2016-08-22 15:42
Hi Nicola.  Could you describe your situation here a bit more? The new plugin uses a different approach for launching apps from the previous plugin (GPE).  

It looks like you're handling the warmup call — what are you doing?

I think this is an instance of #498.  The following error messages generally indicates that we have multiple JVMs trying to connect to the debugger:
```
FATAL ERROR in native method: JDWP No transports initialized, jvmtiError=AGENT_ERROR_TRANSPORT_INIT(197)
ERROR: transport error 202: connect failed: Connection refused
ERROR: JDWP Transport dt_socket failed to initialize, TRANSPORT_INIT(510)
ERROR    2016-08-22 08:50:39,625 http_runtime.py:396] bad runtime process port ['']
```
I'm guessing the `dev_appserver` is causing a new JVM to be launched.

**Comment by NicolaSpreafico** [comment] 2016-08-23 07:26
Hi @briandealwis,

I have indeed a warmup servlet, which is used to warm-up some structure inside the production environment.
```
<servlet>
    <servlet-name>_ah_warmup</servlet-name>
    <servlet-class>it.servlet.WarmupServlet</servlet-class>
</servlet>
```
but as far as I know it should not be triggered inside the dev-server (or at least it is not loaded with the previous dev-server). Maybe the warmup is triggered by web.xml configuration, but does not exists the handler inside the dev-server.

There isn't much to say, I only launch the server and inside the logs this error is shown.

**Comment by chanseokoh** [comment] 2016-08-23 20:25
I figured out why the following error occurs and how to reproduce it. The hint was the line `[default] Detected file changes:`. I filed #604.

```
INFO     2016-08-22 08:50:41,849 module.py:402] [default] Detected file changes:
  WEB-INF\appengine-generated\queue.yaml
INFO     2016-08-22 08:50:42,016 api_server.py:205] Starting API server at: http://localhost:59775
INFO     2016-08-22 08:50:42,395 dispatcher.py:197] Starting module "default" running at: http://localhost:8080
INFO     2016-08-22 08:50:42,397 admin_server.py:116] Starting admin server at: http://localhost:8000
FATAL ERROR in native method: JDWP No transports initialized, jvmtiError=AGENT_ERROR_TRANSPORT_INIT(197)
ERROR: transport error 202: connect failed: Connection refused
ERROR: JDWP Transport dt_socket failed to initialize, TRANSPORT_INIT(510)
ERROR    2016-08-22 08:50:43,767 http_runtime.py:396] bad runtime process port ['']
JDWP exit error AGENT_ERROR_TRANSPORT_INIT(197): No transports initialized [debugInit.c:750]
```

**Comment by chanseokoh** [comment] 2016-08-23 20:26
I think `OperationalError: database is locked` is a separate issue. Here is basically what the error is about: http://stackoverflow.com/questions/26862809/operational-error-database-is-locked

This may or may not be relevant: https://code.google.com/p/googleappengine/issues/detail?id=9935

**Comment by NicolaSpreafico** [comment] 2016-08-24 06:43
Thanks @chanseokoh 

About the `Detected file changes`, my project does not have the `queue.yaml` file but, because of Java project, the counterpart `queue.xml`. Because the yaml file is inside the `appengine-generated` folder, I can guess that the `xml` file is converted to the `yaml` format for the dev-server runtime.
I will follow the #604 for further updates.

About the `database is locked` instead, basing on all the `py` files I can guess the dev-server is python based, even if the project is Java based. From the StackOverflow thread you gave there is a suggestion to restart the server but for me did not works.
I will try to physically remove the datastore files (if exists) and then test again.

**Comment by chanseokoh** [comment] 2016-08-24 14:25
@NicolaSpreafico Thanks for the info. I tested adding `WEB-INF/queue.xml` into a hello-world test app. In my case, however, the dev_appserver doesn't convert it into `queue.yaml`, and I could see the queues I defined are actually there. I wonder if your `queue.xml` has certain specific parameters that trigger the conversion. Or, have you updated both Cloud SDK and App Engine SDK to the latest versions?

One thing you could try, which will also help us diagnose the problem, is to delete your `queue.xml` and copy the generated `queue.yaml` into `WEB-INF/appengine-generated/queue.yaml`. (Note the directory. I verified I could define queues in this way for Java apps.) We could then see if other errors are independent errors or because of the #604.

The `queue.yaml` will be likely in `.metadata/.plugins/org.eclipse.wst.server.core/tmp0/<your app>/WEB-INF/appengine-generated/` in your workspace.

**Comment by briandealwis** [comment] 2016-08-24 14:42
@NicolaSpreafico Do you have an app that you can share to reproduce this?

**Comment by NicolaSpreafico** [comment] 2016-08-25 08:44
@briandealwis I created a brand new project with only a sample code which writes a basic entity inside the datastore (so no warmup request, nothing at all, a plain simple `HelloWorldExample` project)
```
Entity e = new Entity("MyKind");
e.setProperty("property", "value");

DatastoreService ds = DatastoreServiceFactory.getDatastoreService();
ds.put(e);
```

I created a queue.xml file (with a simple queue inside) and I launched the server in DEBUG MODE, with the following startup log.
```
INFO     2016-08-25 10:42:36,789 devappserver2.py:769] Skipping SDK update check.
INFO     2016-08-25 10:42:36,854 api_server.py:205] Starting API server at: http://localhost:55278
INFO     2016-08-25 10:42:36,859 dispatcher.py:197] Starting module "default" running at: http://localhost:8080
INFO     2016-08-25 10:42:36,861 admin_server.py:116] Starting admin server at: http://localhost:8000
ago 25, 2016 10:42:38 AM com.google.appengine.tools.development.SystemPropertiesManager setSystemProperties

Informazioni: Overwriting system property key 'java.util.logging.config.file', value 'C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\tools\java\config\sdk\logging.properties' with value 'WEB-INF/logging.properties' from 'C:\Users\Francesco\workspace_neon\.metadata\.plugins\org.eclipse.wst.server.core\tmp0\testgcs\WEB-INF\appengine-web.xml'

ago 25, 2016 8:42:38 AM com.google.appengine.tools.development.AbstractContainerService configure

Avvertenza: Null value for containerConfigProperties.get(devappserver.portMappingProvider)

ago 25, 2016 8:42:38 AM com.google.apphosting.utils.jetty.JettyLogger info

Informazioni: Logging to JettyLogger(null) via com.google.apphosting.utils.jetty.JettyLogger

ago 25, 2016 8:42:38 AM com.google.apphosting.utils.jetty.JettyLogger info

Informazioni: jetty-6.1.x

ago 25, 2016 8:42:38 AM com.google.apphosting.utils.jetty.JettyLogger info

Informazioni: Started SelectChannelConnector@localhost:55280

ago 25, 2016 8:42:38 AM com.google.appengine.tools.development.AbstractModule startup

Informazioni: Module instance default is running at http://localhost:55280/

ago 25, 2016 8:42:38 AM com.google.appengine.tools.development.AbstractModule startup

Informazioni: The admin console is running at http://localhost:55280/_ah/admin

ago 25, 2016 8:42:38 AM com.google.appengine.tools.development.devappserver2.DevAppServer2Impl doStart

Informazioni: Dev App Server is now running

ago 25, 2016 8:42:41 AM com.google.appengine.tools.development.LocalResourceFileServlet doGet

Avvertenza: No file found for: /_ah/warmup

INFO     2016-08-25 10:42:41,776 module.py:788] default: "GET /_ah/warmup HTTP/1.1" 404 83
```
Please note that the` /_ah/warmup` is anyway hitted even if there is not explicit call inside the web.xml

I made an edit inside the queue.xml file (while the server was still running) and after few seconds the server noticed the file change, with the following log
```
INFO     2016-08-25 10:34:53,907 module.py:402] [default] Detected file changes:
  WEB-INF
  WEB-INF\queue.xml
FATAL ERROR in native method: JDWP No transports initialized, jvmtiError=AGENT_ERROR_TRANSPORT_INIT(197)
ERROR: transport error 202: connect failed: Connection refused
ERROR: JDWP Transport dt_socket failed to initialize, TRANSPORT_INIT(510)
ERROR    2016-08-25 10:34:55,799 http_runtime.py:396] bad runtime process port ['']
JDWP exit error AGENT_ERROR_TRANSPORT_INIT(197): No transports initialized [../../../src/share/back/debugInit.c:750]
ERROR    2016-08-25 10:34:55,868 http_proxy.py:116] bad runtime process port ['']
INFO     2016-08-25 10:34:55,970 module.py:788] default: "GET /_ah/warmup HTTP/1.1" 500 285
```
So I have the same error as you, even if you are using the yaml file and I'm using the xml file.

About the `OperationalError: database is locked` error instead, I'm unable to reproduce it myself so I don't know which steps will be give that error. I can guess that my datastore file was corrupted or in a incosistent state at a time of the issue opening,

**Comment by chanseokoh** [comment] 2016-08-25 12:54
The startup log seems normal. Seeing `/_ah/warmup` is normal. The error seeing after modifying `queue.xml` is exactly #604 as you said, and it will be fixed soon. It looks like there was no auto-generation of `queue.yaml` in your simple example, but after fixing #604, I expect you won't see the original error even if dev_appserver auto-generates `queue.yaml`.

Since you don't see the other errors including `OperationError: database is locked`, they may be transient ones or the ones caused by #604.

**Comment by NicolaSpreafico** [comment] 2016-08-31 06:51
Here we go again,
this error is from another machine where I installed all the components fresh new.

The dev-server was stuck during startup so I had to manually kill-it, maybe this is the behaviour on how to reproduce the problem.
At the moment I'm getting this error during server startup:
```
INFORMAZIONI: Dev App Server is now running

ERROR    2016-08-31 08:35:54,782 module.py:1375] Internal error while handling warmup request.
Traceback (most recent call last):
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\tools\devappserver2\module.py", line 1371, in _warmup
    request_type=instance.READY_REQUEST)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\tools\devappserver2\module.py", line 760, in _handle_request
    module=self._module_configuration.module_name)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\api\apiproxy_stub.py", line 166, in WrappedMethod
    return method(self, *args, **kwargs)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\api\logservice\logservice_stub.py", line 172, in start_request
    host, start_time, method, resource, http_version, module))
OperationalError: database is locked
```
The project is very simple, it is only a `Hello World` Maven example with a couple of lines inside the `HelloAppEngine` servlet

With a couple of test I think i found the proper steps on how reproduce the problem:

1. Run the server in Debug mode
2. Stop the server, the server will remain "alive" due to #597 
3. Even if Eclipse shos the the server is Stopped, inside the Task Manager you can see the running process
4. Hit again the homepage of the server, it is still responding (as confirmation that the process is not stopped)
5. Run again the server in Debug mode, the error is shown

This is probably because, as @briandealwis already mentioned, there is another JVM (the first process which has not be stopped) that is holding the debugger, so another JVM (the second time the server is launched) cannot acquire the debugger

**Comment by briandealwis** [comment] 2016-09-01 17:33
> I get the following message
> bad runtime process port ['']

That usually indicates that something wrote did a `System.out.println()`.

> So I did a more specific read of the active processes, and I found 4 python processes

I suspect you need to go deeper and look at other processes.  Are there any JVMs running?

**Comment by chanseokoh** [comment] 2016-09-01 19:43
Based on @NicolaSpreafico's updates, here is my theory:

- dev_appserver (which is Python) uses the SQLite database (based on a local file) to persist necessary things across multiple local runs.
   - For example, a file called `datastore.db` is created under `/tmp/appengine.myproject.chanseok` on my machine.
   - I see files in that directory are updated whenever you stop a local server or start a new run.
- When dev_appserver is running, it's using the database, so it's holding a lock on it.
- #597 prevents the dev_appserver (as well as the JVM) from terminating. dev_appserver still runs and locks the database.
   - As @NicolaSpreafico said, the server is still serving on 8080, and there are Java and Python processes.
- When trying to run a local server again, it fails because the database is still locked by the previous dev_appserver that is still running.
- As @NicolaSpreafico, if we kill dev_appserver (all the Python process), the problem is gone.

Summary: I think this `OperationalError: database is locked` may be gone once #597 is fixed on Windows. (No guarantee though.)

**Closed** 2017-02-18 04:57 UTC
