### ISSUE TITLE
New Dataflow Project Wizard shows error on start

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/google-cloud-eclipse#2213] opened 2017-08-01 19:31 UTC
Seen in 1.3.0 RC1: Opening a new Dataflow Project wizard immediately shows an error status, contrast to the Eclipse UI guidelines.

<img width="549" alt="screen shot 2017-08-01 at 3 30 05 pm" src="https://user-images.githubusercontent.com/202851/28843218-62bcc9d4-76ce-11e7-9c35-9cb81f6e4d19.PNG">

**Comment by chanseokoh** [comment] 2017-08-01 19:37
Duplicate of #1796.

**Closed by chanseokoh** 2017-08-01 19:37 UTC
Labels: bug, low priority

**Comment by elharo** [comment] 2017-08-01 20:09
Not a blocker, but we should fix this.
