### ISSUE TITLE
Add a library when Maven central can't be reached

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1574] opened 2017-03-11 12:33 UTC
Make sure project isn't borked, and there's a reasonable error message.

**Comment by elharo** [comment] 2017-03-12 12:32
Now awful but we might do better:

![image](https://cloud.githubusercontent.com/assets/1005544/23831793/76ac0b2a-06fe-11e7-9da4-617b8710ee8f.png)

**Comment by elharo** [comment] 2017-03-12 12:35
OTOH, it appears that even after Wifi is reconnected, I still can't create a project.

**Comment by elharo** [comment] 2017-03-12 12:42
Even in a new workspace after a relaunch, this appears to bork new project thoroughly:

Failed to create project - A runtime library is not available locally and cannot be downloaded from the Maven repository: Could not resolve artifact javax.servlet:servlet-api:jar:2.5
Could not resolve artifact javax.servlet:servlet-api:jar:2.5
Failure to transfer javax.servlet:servlet-api:jar:2.5 from https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced. Original error: Could not transfer artifact javax.servlet:servlet-api:jar:2.5 from/to central (https://repo.maven.apache.org/maven2): repo.maven.apache.org: nodename nor servname provided, or not known
Failure to transfer javax.servlet:servlet-api:jar:2.5 from https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced. Original error: Could not transfer artifact javax.servlet:servlet-api:jar:2.5 from/to central (https://repo.maven.apache.org/maven2): repo.maven.apache.org: nodename nor servname provided, or not known

**Comment by elharo** [comment] 2017-03-12 12:49
This appears to be a known Maven issue, not even an m2e issue:

http://stackoverflow.com/questions/4856307/when-maven-says-resolution-will-not-be-reattempted-until-the-update-interval-of

However it does make me a bit more nervous about depending on maven for loading our libraries.

**Comment by chanseokoh** [comment] 2017-03-12 15:00
If this is because the Maven state has been cached locally as in the SO question, it is possible to force rechecking the Maven Central by providing the `-U` option if we were invoking `mvn` on the command line. There may exist a similar option we can use programmatically.

**Comment by elharo** [comment] 2017-03-12 16:56
I feel like we should retry at least once despite the update interval. However I'm not sure how easy this is to force in our code.

**Comment by Purav-Zumkhawala** [comment] 2018-03-14 18:10
Is this error solved cause i am facing the same thing but cant seem to find the solution..

**Comment by chanseokoh** [comment] 2018-03-14 18:22
#2668 is actually a duplicate of this.

@Purav-Zumkhawala please see #2668 to understand what the problem is and how to resolve it. Basically, you should be able to connect to the Maven Central to get necessary JARs. If you can, what you need to do next is to let Maven re-attempt to download the affected JARs. There are actually various ways to do so, but one of the simplest ways is to delete the local JAR folder being affected.

**Comment by diegomarquezp** [comment] 2024-11-19 21:26
Closing as GAE does not support the Java 8 runtime and we don't plan to support later versions. cc: @blakeli0

**Closed by diegomarquezp** 2024-11-19 21:26 UTC
Labels: type: bug, App Engine Standard, priority: p4
