### ISSUE TITLE
Build errors in new project

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1155] opened 2016-12-19 23:57 UTC
In Eclipse 4.7 with new standard project:

![image](https://cloud.githubusercontent.com/assets/1005544/21333324/f6e673ca-c61c-11e6-8df1-fd9b7bcaf243.png)

Maybe the runtime didn't get attached?

**Comment by elharo** [comment] 2016-12-20 00:26
This problem may be unique to 4.7. I don't see it in 4.6.

**Comment by elharo** [comment] 2016-12-20 00:28
Didn't happen again after relaunching 4.7, though the first project is still broken.

**Comment by elharo** [comment] 2016-12-20 00:33
Possibly related from the logs:

java.lang.NullPointerException
	at org.eclipse.equinox.internal.p2.ui.dialogs.CopyUtils.getIndentedClipboardText(CopyUtils.java:42)
	at org.eclipse.equinox.internal.p2.ui.dialogs.ResolutionResultsWizardPage.getClipboardText(ResolutionResultsWizardPage.java:296)
	at org.eclipse.equinox.internal.p2.ui.dialogs.ProvisioningWizardPage.copyToClipboard(ProvisioningWizardPage.java:40)
	at org.eclipse.equinox.internal.p2.ui.dialogs.ResolutionStatusPage.copyToClipboard(ResolutionStatusPage.java:1)
	at org.eclipse.equinox.internal.p2.ui.dialogs.ResolutionResultsWizardPage.copyToClipboard(ResolutionResultsWizardPage.java:1)
	at org.eclipse.equinox.internal.p2.ui.dialogs.SizeComputingWizardPage.copyToClipboard(SizeComputingWizardPage.java:1)
	at org.eclipse.equinox.internal.p2.ui.dialogs.InstallWizardPage.copyToClipboard(InstallWizardPage.java:1)
	at org.eclipse.equinox.internal.p2.ui.dialogs.CopyPopup$1.widgetSelected(CopyPopup.java:36)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:249)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4257)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1501)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1524)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1509)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1313)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4081)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3698)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1133)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:698)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:610)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)

**Comment by elharo** [comment] 2016-12-20 00:34
Unless that's from the other bug. It does come from 4.7. @briandealwis do different instances of Eclipse with different workspaces by any chance share the same error log file?

**Comment by briandealwis** [comment] 2016-12-20 00:35
Seems surprising that this wasn't picked up in the ITs on Oxygen.

**Comment by elharo** [comment] 2016-12-20 00:36
ITs?

**Comment by briandealwis** [comment] 2016-12-20 00:56
Integration tests

**Comment by briandealwis** [comment] 2016-12-20 01:02
Eclipse will by default to the same workspace but it should prompt you to confirm...  There's a change coming to have a default workspace, but I don't think that landed for M4. You can ensure by specifying `-data path/to/directory` when launching.

**Comment by chanseokoh** [comment] 2016-12-20 04:08
Clearly, the jars are missing in your screenshot. I'm curious if the facets are installed and the App Engine runtime is attached.

![selection_007](https://cloud.githubusercontent.com/assets/10523105/21337950/e58fb348-c63f-11e6-93c9-7dc52d095ce5.png)

> Didn't happen again after relaunching 4.7, though the first project is still broken.

Just in case, did you restart 4.7 right after installing (or upgrading) the plugin?

**Comment by chanseokoh** [comment] 2016-12-20 04:28
I found a way to get into the same error state with a good probability (sometimes with different UI error messages), although not sure if the original problem was because of this.

The App Engine facet installation delegate will schedule a job that attaches the runtime, but I think if the job tries to do so before the facet installation is complete (i.e., race condition), there seems to be a good chance of failing to attach the runtime.

**Comment by elharo** [comment] 2016-12-20 10:07
I'm definitely in a different workspace. I was just curious if the log might be shared since the exception stack trace seemed to fit the other bug from a different workspace better.

**Comment by elharo** [comment] 2016-12-20 10:10
In the case where I had the problem:

1. The facet was installed.
2. A runtime existed (I think) but was not selected. Unless the runtime I saw was created for the second project in that workspace. Very likely the problem is somewhere in runtime creation and attachment.

**Comment by elharo** [comment] 2016-12-20 11:21
@chanseokoh Good idea. I'm not immediately sure how to address it. We need to pause the installJob until the facet installation is complete. 

Perhaps we can wait on an object in installJob.run and then notify that object at the end of CreateAppEngineStandardWtpProject.execute or AppEngineStandardFacet.installAppEngineFacet?

Eclipse has scheduling rules for Jobs, but I'm not sure those work here since the installation of the App Engine facet doesn't happen in a job.

**Comment by briandealwis** [comment] 2016-12-20 15:19
If that's the case @chanseokoh then we should be able to cause the runtime-creation job to wait on any pending builds similar to `ProjectUtilities#waitForIdle()`.

It seems like we should create this runtime on startup or Cloud SDK change so that we can guarantee it's available.

**Comment by chanseokoh** [comment] 2016-12-20 16:03
I can reproduce this by adding `Thread.sleep()` at the end of `StandardFacetInstallDelegate.execute()` as below and repeatedly creating a new native project. It increases the chance of getting into the error state.

```java
    ...
    installAppEngineRuntimes(project);
    try {
      Thread.sleep(1000);
    } catch (InterruptedException e) {}
  }
```

What I don't understand, however, is that, I can't reproduce this when I just repeatedly uninstall/install the App Engine facet alone. Interestingly, I can reproduce this when I repeatedly uninstall/install the App Engine facet and the Dynamic Web facet together. There may be more than we think now.

> It seems like we should create this runtime on startup or Cloud SDK change so that we can guarantee it's available.

So, it's not only the availability of the runtime, since I can reproduce this while the runtime is there.

**Comment by elharo** [comment] 2016-12-20 16:12
@briandealwis Do you mean `SwtBotWorkbenchActions#waitForIdle`?

**Comment by briandealwis** [comment] 2016-12-20 16:14
Sorry was typing from memory: https://github.com/GoogleCloudPlatform/google-cloud-eclipse/blob/master/plugins/com.google.cloud.tools.eclipse.test.util/src/com/google/cloud/tools/eclipse/test/util/project/ProjectUtils.java#L161

**Comment by elharo** [comment] 2016-12-20 16:19
In other words, something like this?

      Job installJob = new Job("Install App Engine runtimes in " + project.getName()) {
      @Override
      protected IStatus run(IProgressMonitor monitor) {
        try {
          ProjectUtils.waitUntilIdle();
          IFacetedProject facetedProject = ProjectFacetsManager.create(project);
          AppEngineStandardFacet.installAllAppEngineRuntimes(facetedProject, monitor);
          return Status.OK_STATUS;
        } catch (CoreException ex) {
          return ex.getStatus();
        }
      }
    };

**Comment by briandealwis** [comment] 2016-12-20 16:19
I haven't looked at the code yet, but IIRC the `installAppEngineRuntimes` code looks to see if the AES facet is installed and skips the installation — [@chanseok's race condition](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/1155#issuecomment-268152054).  We could just use a semaphore or an Eclipse Jobs Lock to synchronize the jobs.

**Comment by elharo** [comment] 2016-12-20 16:25
Yes, I'm trying to understand where's the Job we lock to. `installAppEngineRuntimes` takes place in one Job, but I'm not sure what job (if any) is running CreateAppEngineStandardWtpProject

**Comment by briandealwis** [comment] 2016-12-20 17:57
When it happens, I see an error logged:
```
!ENTRY org.eclipse.wst.common.project.facet.core 4 0 2016-12-20 12:54:58.527
!MESSAGE Primary runtime has to be one of the targeted runtimes.
```

**Comment by briandealwis** [comment] 2016-12-20 18:03
I instrumented some methods on `FacetedProject` to log calls, and `AppEngineStandardRuntimeChangeListener` to see if it was somehow conflicting.  Note that after ``setTargetedRuntimes([App Engine Standard Runtime])` it is then removed again with `setTargetedRuntimes([])`.
```
FacetedProject.installProjectFacet(Java 1.7)
FacetedProject.setTargetedRuntimes([])
FacetedProject.installProjectFacet(Dynamic Web Module 2.5)
FacetedProject.setTargetedRuntimes([])
FacetedProject.installProjectFacet(App Engine Java Standard Environment 1)
FacetedProject.setTargetedRuntimes([])
>> JOB: StandardFacetInstallDelegate.installAppEngineRuntimes(P/foo)
FacetedProject.addTargetedRuntime(App Engine Standard Runtime)
FacetedProject.installProjectFacet(JavaScript 1.0)
FacetedProject.setTargetedRuntimes([])
FacetedProject.setTargetedRuntimes([App Engine Standard Runtime])
>> AppEngineStandardRuntimeChangeListener: event=PRIMARY_RUNTIME_CHANGED
++ AppEngineStandardRuntimeChangeListener: newRuntime=App Engine Standard Runtime
<< AppEngineStandardRuntimeChangeListener: skipping as project has AppEngineFacet
FacetedProject.setTargetedRuntimes([])
>> AppEngineStandardRuntimeChangeListener: event=PRIMARY_RUNTIME_CHANGED
++ AppEngineStandardRuntimeChangeListener: newRuntime=null
<< AppEngineStandardRuntimeChangeListener: skipping as null runtime
FacetProject.setPrimaryRuntime(App Engine Standard Runtime)
FacetProject.setPrimaryRuntimeInternal(App Engine Standard Runtime)

!ENTRY org.eclipse.wst.common.project.facet.core 4 0 2016-12-20 12:56:52.034
!MESSAGE Primary runtime has to be one of the targeted runtimes.
FacetedProject.setTargetedRuntimes([])
```

**Comment by briandealwis** [comment] 2016-12-20 18:11
I caused `FacetedProject#setTargetedRuntimesInternal()` to print a stack trace of callers and the culprit appears to be a `ConvertJob` that installs the JavaScript facet, spawned by installing the Dynamic Web Project facet.
```
FacetedProject.addTargetedRuntime(App Engine Standard Runtime)
FacetedProject.installProjectFacet(JavaScript 1.0)
java.lang.Throwable: FacetedProject.setTargetedRuntimesInternal: []
	at org.eclipse.wst.common.project.facet.core.internal.FacetedProject.setTargetedRuntimesInternal(FacetedProject.java:669)
	at org.eclipse.wst.common.project.facet.core.internal.FacetedProject.mergeChangesInternal(FacetedProject.java:1161)
	at org.eclipse.wst.common.project.facet.core.internal.FacetedProject.access$2(FacetedProject.java:1117)
	at org.eclipse.wst.common.project.facet.core.internal.FacetedProject$1.run(FacetedProject.java:324)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2241)
	at org.eclipse.wst.common.project.facet.core.internal.FacetedProject.modify(FacetedProject.java:339)
	at org.eclipse.wst.common.project.facet.core.internal.FacetedProject.installProjectFacet(FacetedProject.java:255)
	at org.eclipse.wst.jsdt.web.core.internal.project.ConvertJob.runInWorkspace(ConvertJob.java:57)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
java.lang.Throwable: FacetedProject.setTargetedRuntimesInternal: [App Engine Standard Runtime]
	at org.eclipse.wst.common.project.facet.core.internal.FacetedProject.setTargetedRuntimesInternal(FacetedProject.java:669)
	at org.eclipse.wst.common.project.facet.core.internal.FacetedProject.access$4(FacetedProject.java:663)
	at org.eclipse.wst.common.project.facet.core.internal.FacetedProject$3.run(FacetedProject.java:645)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2241)
	at org.eclipse.wst.common.project.facet.core.internal.FacetedProject.setTargetedRuntimes(FacetedProject.java:655)
	at org.eclipse.wst.common.project.facet.core.internal.FacetedProject.addTargetedRuntime(FacetedProject.java:771)
	at com.google.cloud.tools.eclipse.appengine.facets.AppEngineStandardFacet.installAllAppEngineRuntimes(AppEngineStandardFacet.java:163)
	at com.google.cloud.tools.eclipse.appengine.facets.StandardFacetInstallDelegate$1.run(StandardFacetInstallDelegate.java:64)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55
```

**Comment by briandealwis** [comment] 2016-12-20 18:14
I think this is our fault as it looks like we're not running under a `WorkspaceModifyOperation`.

**Comment by chanseokoh** [comment] 2016-12-20 18:55
| @briandealwis I think part of the issue is that the `ConvertJob` doesn't seem to run with a lock/scheduling rule

Possibly. I also see that someone calls `setTargetedRuntimeInternal([])` (i.e., clearing all added runtimes) after we call `setTargetedRuntimeInternal([App Engine Standard Runtime])`. If `ConvertJob` is at fault of not locking, it could be a bit tricky to resolve this flawlessly.

**Comment by briandealwis** [comment] 2016-12-20 19:38
A few things we've discovered.

#### The issue cannot be worked around by explicitly adding a JavaScript facet

The `ConvertJob` is created by a listener that reacts to facet changes like the addition of the dynamic web facet.  Unfortunately explicitly adding the JavaScript facet doesn't make a difference.
```
Thread [ModalContext] (Suspended (breakpoint at line 42 in FacetedProjectListener))	
	owns: CreateAppEngineStandardWtpProject  (id=1452)	
	FacetedProjectListener.handleEvent(IFacetedProjectEvent) line: 42	
	DelayedClassLoadingListener.handleEvent(IFacetedProjectEvent) line: 62	
	ProjectListenerRegistry.notifyListeners(IFacetedProjectEvent) line: 76	
	FacetedProject.notifyListeners(IFacetedProjectEvent) line: 1327	
	FacetedProject.modifyInternal(Set<Action>, IProgressMonitor) line: 454	
	FacetedProject.mergeChangesInternal(IFacetedProjectWorkingCopy, IProgressMonitor) line: 1181	
	FacetedProject.access$2(FacetedProject, IFacetedProjectWorkingCopy, IProgressMonitor) line: 1117	
	FacetedProject$1.run(IProgressMonitor) line: 324	
	Workspace.run(IWorkspaceRunnable, ISchedulingRule, int, IProgressMonitor) line: 2241	
	FacetedProject.modify(Set<Action>, IProgressMonitor) line: 339	
	FacetedProject.installProjectFacet(IProjectFacetVersion, Object, IProgressMonitor) line: 255	
	AppEngineStandardFacet.installWebFacet(IFacetedProject, IProgressMonitor) line: 238	
	AppEngineStandardFacet.installAppEngineFacet(IFacetedProject, boolean, IProgressMonitor) line: 125	
	CreateAppEngineStandardWtpProject.execute(IProgressMonitor) line: 102	
	WorkspaceModifyOperation$1.run(IProgressMonitor) line: 108	
	Workspace.run(IWorkspaceRunnable, ISchedulingRule, int, IProgressMonitor) line: 2241	
	CreateAppEngineStandardWtpProject(WorkspaceModifyOperation).run(IProgressMonitor) line: 130	
	ModalContext$ModalContextThread.run() line: 119	
```

## The `ConvertJob` acquires a workspace lock too late

The public operations on `FacetedProject`, like `setTargetedRuntime()` (called from our `installAllAppEngineRuntimes()`) and `mergeChanges()` (called from `ConvertJob`) are run with the workspace lock.  The problem here is that the the `ConvertJob` is configured to perform its changes against a working copy of the faceted project, which is done without the workspace lock; only the `mergeChanges()` is performed with the workspace lock.  If we [monkey-patch](https://rgrunber.wordpress.com/2016/12/09/hot-code-replace-with-the-breakpoint-properties-page-in-eclipse/) `ConvertJob`'s constructor to set the project as its scheduling rule, then the jobs are scheduled nicely and there's no interference.

**Comment by chanseokoh** [comment] 2016-12-21 00:16
@briandealwis Superb work! This was a very annoying problem and has been really painful to analyze.

Brian did a wonderful job to get to the bottom of this problem, figuring out the root cause. He proposed a fix ([branch bsd-1155](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/tree/bsd-1155)) before he left early. The fix significantly reduces the chance of triggering this issue, perhaps to almost zero in practice.

The fix still has a theoretical loophole, although it's probably very unlikely that this loophole is triggered. That's why I said the fix "significantly reduces the chance." I have pushed a carefully crafted simulation that will always trigger this loophole in [this branch](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/tree/bsd-1155-unlucky-case). @briandealwis, this will be interesting to you. The following console output summarizes the scenario:

```
ConvertJob: took a snapshot with an empty runtime list.
ConvertJob: will wait until installJob installs App Engine runtime.
>> InstallAppEngineRuntimesJob[6.521 ms]: is dirty, will try again
>> InstallAppEngineRuntimesJob[72.28 ms]: is dirty, will try again
>> InstallAppEngineRuntimesJob[149.5 ms]: is dirty, will try again
>> InstallAppEngineRuntimesJob[244.6 ms]: is dirty, will try again
>> InstallAppEngineRuntimesJob[339.6 ms]: is dirty, will try again
>> InstallAppEngineRuntimesJob[440.5 ms]: is dirty, will try again
>> InstallAppEngineRuntimesJob[541.4 ms]: is dirty, will try again
>> InstallAppEngineRuntimesJob[642.3 ms]: is dirty, will try again
>> InstallAppEngineRuntimesJob[730.2 ms]: is dirty, will try again
>> InstallAppEngineRuntimesJob[800.3 ms]: is dirty, will try again
>> InstallAppEngineRuntimesJob[872.5 ms]: is dirty, will try again
>> InstallAppEngineRuntimesJob[924.0 ms]: is dirty, will try again
>> InstallAppEngineRuntimesJob[975.2 ms]: is dirty, will try again
>> InstallAppEngineRuntimesJob[1.041 s]: is dirty, will try again
>> InstallAppEngineRuntimesJob[1.131 s]: is dirty, will try again
>> InstallAppEngineRuntimesJob[1.228 s]: GO: installing runtimes
InstallJob: installed App Engine runtime.
InstallJob: will wake up ConvertJob to overwrite the runtime list.
ConvertJob: reset the runtime list. It's empty now.
```

That said, I wasn't able to think of an ultimate solution. I think the best we can do is to reduce the chance of this happening to almost zero in practice. I think waiting until JSDT is installed, and perhaps waiting for a little bit more after that is sufficient.

**Comment by briandealwis** [comment] 2016-12-21 02:20
You're right @chanseok — I forgot that we'rr supposed to wait until `ConvertJob` adds the JSDT facet as a *fixed* facet, not just a general facet.  All of this is so targeted to`ConvertJob` 😕... I wonder if there is any merit to monitoring for any other jobs scheduled?

**Comment by briandealwis** [comment] 2016-12-21 03:09
The other thing to look at is whether we can suspended the`JobManager`.

**Comment by chanseokoh** [comment] 2016-12-21 15:21
This is so annoying. `ConvertJob` schedules another `ConvertJob` when it calls `installProjectFacet(JSDT)`. (The call executes the JSDT facet delegate (`JsNatureInstaller.execute()`) synchronously, and before `installProjectFacet(JSDT)` returns, the second `ConvertJob` is scheduled.) Any code line of the second `ConvertJob` can execute anytime once it's running. We may check if the first `ConvertJob` is basically done by checking if it added JSDT as a fixed facet, but for the second `ConvertJob`, there is no good way we can check its completion. In fact, it's theoretically possible that the two `ConvertJob`s run concurrently and ruin each other (and us).

**Closed** 2017-01-04 03:25 UTC
Labels: bug, GA, high priority

**Comment by briandealwis** [comment] 2017-01-12 03:32
I tried experimenting with a different approach (see branch [alternative-1167](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/tree/alternative-1167)).  Instead of automagically installing the AES Runtime via a job (#1099), creating a project explicitly installs the AES Runtime _before_ we add the AES, Dynamic Web, and Java facets.  Thus the project's runtime is set before the `ConvertJob` is ever triggered and sidestepping the contention.

But this approach doesn't address the situation where a user uses the _Project Facets_ property page to select the AES Facet and forgets to add the AES Runtime.  It turns out that a facet can be installed with a configuration/context object (e.g., to specify the location of the `WEB-INF` directory for a _Dynamic Web Project_).  If that object extends `ActionConfig` then faceted framework will call `ActionConfig#validate()` (returns an `IStatus`) as part of the facet validation process.  I experimented creating a facet `StandardFacetActionConfig` object for our AES facet whose `#validate()` checks that the project has an AES Runtime and returns an error if not found.  This kinda works, but it's suboptimal.  `#validate()` is intended to validate the facet's configuration settings (e.g., that the _Dynamic Web Project_ specifies a valid directory for the context root).  Errors are intended to be fixed via a facet wizard page (configured via the `org.eclipse.wst.common.project.facet.ui.wizardPage` extension point). When `#validate()` returns an error then the "Further configuration available" hyperlink (that opens the available wizard pages) becomes _"Further configuration required"_ with a little red "X" (see below).  But the validation status object is otherwise tossed and the status message is never shown.  Clicking on the further-configuration hyperlink pops up the facet wizard pages (as shown in the _Modify_ dialog).  The only option then is to provide a facet wizard page to display the error?

The only other option I can think of is to keep the facet-listening job but instead prompt the user whether they want to add the AES Runtime.  That may delay enough that the `ConvertJob` will have already executed.

<img width="834" alt="tmp-519axmsktcap3ew" src="https://cloud.githubusercontent.com/assets/202851/21875362/51e6fbd0-d849-11e6-8df3-d0b3983d6a25.png">

**Comment by briandealwis** [comment] 2017-01-12 16:13
Filed as [bug 510377](https://bugs.eclipse.org/bugs/show_bug.cgi?id=510377).

**Comment by chanseokoh** [comment] 2017-01-12 16:28
Thanks for filing the bug, @briandealwis.

**Comment by chanseokoh** [comment] 2017-06-21 15:50
Adding a quick summary of what had been the problem:

```
Our job    ---------------------|---------------------------------

                                ^
                                |
                       Makes some changes (added a runtime)

ConvertJob --|------------------------------------------|---------

             ^                                          ^
             |                                          |
          Creates a WC                           commitChanges()
                                             This does not work like
                                             git commit; it overwrites
                                             facet changes from our job
```
